import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'es', 'tl', 'fr', 'zh_Hans'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? tlText = '',
    String? frText = '',
    String? zh_HansText = '',
  }) =>
      [enText, esText, tlText, frText, zh_HansText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login
  {
    'hxiwpwui': {
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'tl': 'Lumikha ng Account',
      'zh_Hans': '创建账户',
    },
    'exun2xyq': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'unvb2xpi': {
      'en': 'YourName@example.com',
      'es': 'TuNombre@ejemplo.com',
      'fr': 'VotreNom@exemple.com',
      'tl': 'YourName@example.com',
      'zh_Hans': '您的姓名@example.com',
    },
    'y5a6love': {
      'en': 'Phone Number',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'tl': 'Numero ng telepono',
      'zh_Hans': '电话号码',
    },
    '1wj9h04k': {
      'en': 'Must include country Code (+1 for USA)',
      'es': 'Debe incluir el código de país (+1 para EE. UU.)',
      'fr': 'Doit inclure le code du pays (+1 pour les États-Unis)',
      'tl': 'Dapat isama ang Code ng bansa (+1 para sa USA)',
      'zh_Hans': '必须包含国家代码（+1 代表美国）',
    },
    '7c3ot4wz': {
      'en': 'First Name',
      'es': 'Nombre de pila',
      'fr': 'Prénom',
      'tl': 'Pangalan',
      'zh_Hans': '名',
    },
    'fly5shpv': {
      'en': 'Last Name',
      'es': 'Apellido',
      'fr': 'Nom de famille',
      'tl': 'Huling pangalan',
      'zh_Hans': '姓',
    },
    'vit8m0nm': {
      'en': 'Opt in to pigs and promotions in your email',
      'es': 'Suscríbete a cerdos y promociones en tu correo electrónico',
      'fr': 'Inscrivez-vous aux cochons et aux promotions dans votre e-mail',
      'tl': 'Mag-opt in sa mga baboy at promosyon sa iyong email',
      'zh_Hans': '选择在您的电子邮件中接收猪和促销信息',
    },
    '5tlavdfn': {
      'en': 'Get Started',
      'es': 'Empezar',
      'fr': 'Commencer',
      'tl': 'Magsimula',
      'zh_Hans': '立即开始',
    },
    '7kx1mid1': {
      'en': 'Legal Stuff',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o3reyrbh': {
      'en': 'Log In',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'tl': 'Mag log in',
      'zh_Hans': '登录',
    },
    'qw06jci8': {
      'en': 'Welcome Back',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'tl': 'Maligayang pagbabalik',
      'zh_Hans': '欢迎回来',
    },
    'e2kqv3tf': {
      'en': 'Fill out the information below in order to access your account.',
      'es': 'Complete la información a continuación para acceder a su cuenta.',
      'fr':
          'Remplissez les informations ci-dessous afin d\'accéder à votre compte.',
      'tl': 'Punan ang impormasyon sa ibaba upang ma-access ang iyong account.',
      'zh_Hans': '填写以下信息以访问您的帐户。',
    },
    'f6rvgfs7': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'af2n62ur': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'tl': 'Password',
      'zh_Hans': '密码',
    },
    'klva35si': {
      'en': 'Sign In',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'tl': 'Mag-sign In',
      'zh_Hans': '登入',
    },
    'i0bf9sho': {
      'en': 'Forgot Password?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'tl': 'Nakalimutan ang password?',
      'zh_Hans': '忘记密码？',
    },
    'iyfjsk7h': {
      'en': 'Accept Invitation',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'tl': 'Nakalimutan ang password?',
      'zh_Hans': '忘记密码？',
    },
    'dzpfqy54': {
      'en': 'Verify Email',
      'es': 'Verificar correo electrónico',
      'fr': 'Vérifier les courriels',
      'tl': 'I-verify ang Email',
      'zh_Hans': '验证邮件',
    },
    'kfoiiu67': {
      'en': 'Legal Stuff',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lu7sjzp3': {
      'en': 'Disclaimer: The Purple Piggy Bank LLC is not a bank. ',
      'es':
          'Descargo de responsabilidad: Purple Piggy Bank LLC no es un banco.',
      'fr': 'Avertissement : La Purple Piggy Bank LLC n\'est pas une banque.',
      'tl': 'Disclaimer: Ang Purple Piggy Bank LLC ay hindi isang bangko.',
      'zh_Hans': '免责声明：Purple Piggy Bank LLC 不是银行。',
    },
    '9iag3u40': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // ConfirmEmail
  {
    '2jxqetp7': {
      'en': 'Check your email for a confirmation code and enter it below',
      'es':
          'Revise su correo electrónico para obtener un código de confirmación e ingréselo a continuación',
      'fr':
          'Vérifiez votre e-mail pour un code de confirmation et saisissez-le ci-dessous',
      'tl':
          'Suriin ang iyong email para sa isang confirmation code at ilagay ito sa ibaba',
      'zh_Hans': '检查您的电子邮件以获取确认码并在下面输入',
    },
    'yfq6xx64': {
      'en': 'Email ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'je3ymwzg': {
      'en': 'Confirm Email',
      'es': 'Confirmar correo electrónico',
      'fr': 'Confirmez votre email',
      'tl': 'Kumpirmahin ang Email',
      'zh_Hans': '确认电子邮件',
    },
    'pff0v29d': {
      'en': 'Confirm Email',
      'es': 'Confirmar correo electrónico',
      'fr': 'Confirmez votre email',
      'tl': 'Kumpirmahin ang Email',
      'zh_Hans': '确认电子邮件',
    },
    'qsrie90l': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // ForgotPassword
  {
    '8o3c8w94': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'tl': 'Email Address',
      'zh_Hans': '电子邮件地址',
    },
    '4g9wlh73': {
      'en': 'Send Me A Reset Code',
      'es': 'Envíame un código de reinicio',
      'fr': 'Envoyez-moi un code de réinitialisation',
      'tl': 'Padalhan Ako ng Reset Code',
      'zh_Hans': '发送重置代码给我',
    },
    'yvhi0k3e': {
      'en': 'Forgot Password',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'tl': 'Nakalimutan ang password',
      'zh_Hans': '忘记密码',
    },
    'mo5n9cmm': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // PasswordResetCode
  {
    '8lk6slas': {
      'en': 'Check your email for a confirmation code and enter it below',
      'es':
          'Revise su correo electrónico para obtener un código de confirmación e ingréselo a continuación',
      'fr':
          'Vérifiez votre e-mail pour un code de confirmation et saisissez-le ci-dessous',
      'tl':
          'Suriin ang iyong email para sa isang confirmation code at ilagay ito sa ibaba',
      'zh_Hans': '检查您的电子邮件以获取确认码并在下面输入',
    },
    'e3azezwx': {
      'en': 'Email ',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'gysxne8w': {
      'en': 'New Password',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'tl': 'Bagong Password',
      'zh_Hans': '新密码',
    },
    'g8ki1rg8': {
      'en': 'New Password',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'tl': 'Bagong Password',
      'zh_Hans': '新密码',
    },
    'xlv8tjrt': {
      'en': 'Set New Password',
      'es': 'Establecer nueva contraseña',
      'fr': 'Definir un nouveau mot de passe',
      'tl': 'Magtakda ng Bagong Password',
      'zh_Hans': '设置新密码',
    },
    'nic9w7r8': {
      'en': 'Reset Password',
      'es': 'Restablecer la contraseña',
      'fr': 'réinitialiser le mot de passe',
      'tl': 'I-reset ang Password',
      'zh_Hans': '重设密码',
    },
    'ox6veo0p': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // CreateHousehold
  {
    '28tml14z': {
      'en':
          'At The Purple Piggy Bank, a \"Household\" is a grouping of budgets. \nYou can name it anything you want.',
      'es':
          'En The Purple Piggy Bank, un \"hogar\" es una agrupación de presupuestos. \nPuedes nombrarlo como quieras.',
      'fr':
          'Chez La Tirelire Pourpre, un « Ménage » est un regroupement de budgets. \nVous pouvez le nommer comme vous le souhaitez.',
      'tl':
          'Sa The Purple Piggy Bank, ang \"Household\" ay isang pagpapangkat ng mga badyet. \nMaaari mo itong pangalanan kahit anong gusto mo.',
      'zh_Hans': '在紫色小猪银行，“家庭”是指一组预算。\n您可以随意命名。',
    },
    'q5a1tx49': {
      'en': 'Household Name',
      'es': 'Nombre del hogar',
      'fr': 'Nom du ménage',
      'tl': 'Pangalan ng Sambahayan',
      'zh_Hans': '家喻户晓',
    },
    's9e7nrfw': {
      'en': 'Create',
      'es': 'Crear',
      'fr': 'Créer',
      'tl': 'Lumikha',
      'zh_Hans': '创造',
    },
    'qrqf5ejm': {
      'en': 'New Household',
      'es': 'Nuevo hogar',
      'fr': 'Nouveau ménage',
      'tl': 'Bagong Sambahayan',
      'zh_Hans': '新家居',
    },
    'n7u54he6': {
      'en': 'Household',
      'es': 'Familiar',
      'fr': 'Ménage',
      'tl': 'Sambahayan',
      'zh_Hans': '家庭',
    },
  },
  // AddInvite
  {
    'sr862bzk': {
      'en': 'Invitations',
      'es': 'Invitaciones',
      'fr': 'Invitations',
      'tl': 'Mga imbitasyon',
      'zh_Hans': '邀请',
    },
    '6jye0bmc': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'nyddug4b': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'fvt4duqj': {
      'en': 'Select Household',
      'es': 'Seleccione Hogar',
      'fr': 'Sélectionnez le foyer',
      'tl': 'Piliin ang Sambahayan',
      'zh_Hans': '选择家庭',
    },
    'hcezr687': {
      'en': 'Invite other people to join your Household',
      'es': 'Invita a otras personas a unirse a tu hogar',
      'fr': 'Invitez d\'autres personnes à rejoindre votre foyer',
      'tl': 'Mag-imbita ng ibang tao na sumali sa iyong Sambahayan',
      'zh_Hans': '邀请其他人加入你的家庭',
    },
    'gkhj25dd': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    '2bwn6o90': {
      'en': 'Send Invitation',
      'es': 'Enviar invitacion',
      'fr': 'Envoyer une invitation',
      'tl': 'Magpadala ng imbitasyon',
      'zh_Hans': '发送邀请',
    },
    'fe3uvau5': {
      'en': 'Invite',
      'es': 'Invitar',
      'fr': 'Inviter',
      'tl': 'Mag-anyaya',
      'zh_Hans': '邀请',
    },
  },
  // AcceptInvite
  {
    'sxb2lz9l': {
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'tl': 'Lumikha ng Account',
      'zh_Hans': '创建账户',
    },
    '2jabljnl': {
      'en': 'Let\'s get started by filling out the form below.',
      'es': 'Comencemos completando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'tl': 'Magsimula tayo sa pamamagitan ng pagsagot sa form sa ibaba.',
      'zh_Hans': '让我们从填写下面的表格开始。',
    },
    'hjpdhn03': {
      'en': 'Invitation Code',
      'es': 'código de invitación',
      'fr': 'code d\'invitation',
      'tl': 'Code ng Imbitasyon',
      'zh_Hans': '邀请代码',
    },
    '2pxecvbu': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'tdziz6ej': {
      'en': 'First Name',
      'es': 'Nombre de pila',
      'fr': 'Prénom',
      'tl': 'Pangalan',
      'zh_Hans': '名',
    },
    'do882gxg': {
      'en': 'Last Name',
      'es': 'Apellido',
      'fr': 'Nom de famille',
      'tl': 'Huling pangalan',
      'zh_Hans': '姓',
    },
    'wqmswne9': {
      'en': 'Phone Number',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'tl': 'Numero ng telepono',
      'zh_Hans': '电话号码',
    },
    'q854splb': {
      'en': 'Must include country Code (+1 for USA)',
      'es': 'Debe incluir el código de país (+1 para EE. UU.)',
      'fr': 'Doit inclure le code du pays (+1 pour les États-Unis)',
      'tl': 'Dapat isama ang Code ng bansa (+1 para sa USA)',
      'zh_Hans': '必须包含国家代码（+1 代表美国）',
    },
    '02smpn20': {
      'en': 'Opt into getting pigs and promotions in your email inbox!',
      'es':
          '¡Opta por recibir cerdos y promociones en tu bandeja de entrada de correo electrónico!',
      'fr':
          'Choisissez de recevoir des cochons et des promotions dans votre boîte de réception e-mail !',
      'tl':
          'Mag-opt in sa pagkuha ng mga baboy at promosyon sa iyong email inbox!',
      'zh_Hans': '选择在您的电子邮件收件箱中接收猪和促销信息！',
    },
    '33j66c20': {
      'en': 'Get Started',
      'es': 'Empezar',
      'fr': 'Commencer',
      'tl': 'Magsimula',
      'zh_Hans': '立即开始',
    },
    'b2876cm5': {
      'en': 'Accept Invite',
      'es': 'Aceptar invitación',
      'fr': 'Accepter l\'invitation',
      'tl': 'Tanggapin ang Imbitasyon',
      'zh_Hans': '接受邀请',
    },
    '6jhoz580': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // AddPaymentSource
  {
    'kdis00po': {
      'en':
          'Add a payment source - This is a way to group where money comes from in your budget.',
      'es':
          'Agregar una fuente de pago: esta es una forma de agrupar de dónde proviene el dinero en su presupuesto.',
      'fr':
          'Ajouter une source de paiement : c\'est un moyen de regrouper la provenance de l\'argent dans votre budget.',
      'tl':
          'Magdagdag ng pinagmumulan ng pagbabayad - Ito ay isang paraan upang pagpangkatin kung saan nanggagaling ang pera sa iyong badyet.',
      'zh_Hans': '添加付款来源-这是对预算中的资金来源进行分组的一种方法。',
    },
    'zqrj2y9j': {
      'en': 'Checking Account',
      'es': 'Cuenta de cheques',
      'fr': 'Compte courant',
      'tl': 'Checking Account',
      'zh_Hans': '支票账户',
    },
    'e52l5u4z': {
      'en': 'Savings Account',
      'es': 'Cuenta de ahorros',
      'fr': 'Compte épargne',
      'tl': 'Savings Account',
      'zh_Hans': '储蓄账户',
    },
    'mi5fc5tx': {
      'en': 'Credit Card',
      'es': 'Tarjeta de crédito',
      'fr': 'Carte de crédit',
      'tl': 'Credit Card',
      'zh_Hans': '信用卡',
    },
    '6px80htj': {
      'en': 'Loan',
      'es': 'Préstamo',
      'fr': 'Prêt',
      'tl': 'Pautang',
      'zh_Hans': '贷款',
    },
    '92qq1pgp': {
      'en': 'Other',
      'es': 'Otro',
      'fr': 'Autre',
      'tl': 'Iba pa',
      'zh_Hans': '其他',
    },
    '0ena8ip9': {
      'en': 'Please select what kind of Account...',
      'es': 'Por favor seleccione qué tipo de cuenta...',
      'fr': 'Veuillez sélectionner quel type de compte...',
      'tl': 'Mangyaring piliin kung anong uri ng Account...',
      'zh_Hans': '请选择帐户类型...',
    },
    'jpavqzma': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'ck4wkfxe': {
      'en': 'Source Name',
      'es': 'Nombre de la fuente',
      'fr': 'Nom de la source',
      'tl': 'Pangalan ng Pinagmulan',
      'zh_Hans': '源名称',
    },
    'iy11i9yj': {
      'en': 'Enter source name...',
      'es': 'Introduzca el nombre de la fuente...',
      'fr': 'Entrez le nom de la source...',
      'tl': 'Ilagay ang pangalan ng pinagmulan...',
      'zh_Hans': '输入源名称...',
    },
    'lljo571u': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    'gpf0bbl8': {
      'en': 'Enter source name...',
      'es': 'Introduzca el nombre de la fuente...',
      'fr': 'Entrez le nom de la source...',
      'tl': 'Ilagay ang pangalan ng pinagmulan...',
      'zh_Hans': '输入源名称...',
    },
    'r9ydgouh': {
      'en': 'Create Payment Source',
      'es': 'Crear fuente de pago',
      'fr': 'Créer une source de paiement',
      'tl': 'Lumikha ng Pinagmulan ng Pagbabayad',
      'zh_Hans': '创建付款来源',
    },
    'ro0op7rj': {
      'en': 'Add Wallet',
      'es': 'Agregar billetera',
      'fr': 'Ajouter un portefeuille',
      'tl': 'Magdagdag ng Wallet',
      'zh_Hans': '添加钱包',
    },
    '2sxctoc7': {
      'en': 'Source',
      'es': 'Fuente',
      'fr': 'Source',
      'tl': 'Pinagmulan',
      'zh_Hans': '来源',
    },
  },
  // AddTransaction
  {
    '6cb881qe': {
      'en': 'example',
      'es': 'ejemplo',
      'fr': 'exemple',
      'tl': 'halimbawa',
      'zh_Hans': '例子',
    },
    'j9y0ullm': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'drxj8fg1': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'qv1kzk04': {
      'en': 'Select Household*',
      'es': 'Seleccione Hogar*',
      'fr': 'Sélectionnez un foyer*',
      'tl': 'Pumili ng Sambahayan*',
      'zh_Hans': '选择家庭*',
    },
    '6mox1rnq': {
      'en': 'Please Select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'srs8ebvc': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '02i8v3nh': {
      'en': 'Select Payment Source*',
      'es': 'Seleccione fuente de pago*',
      'fr': 'Sélectionnez la source de paiement*',
      'tl': 'Piliin ang Pinagmulan ng Pagbabayad*',
      'zh_Hans': '选择付款来源*',
    },
    'g5ahcttr': {
      'en': 'Debit',
      'es': 'Débito',
      'fr': 'Débit',
      'tl': 'Utang',
      'zh_Hans': '借方',
    },
    'yn02ubpd': {
      'en': '-',
      'es': '-',
      'fr': '-',
      'tl': '-',
      'zh_Hans': '-',
    },
    '7sd71dvf': {
      'en': '+',
      'es': '+',
      'fr': '+',
      'tl': '+',
      'zh_Hans': '+',
    },
    'dvk73hmh': {
      'en': 'Please Select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'xslgp9zr': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'jijiw4uw': {
      'en': '+/-',
      'es': '+/-',
      'fr': '+/-',
      'tl': '+/-',
      'zh_Hans': '+/-',
    },
    'cc1crqyo': {
      'en': 'Amount*',
      'es': 'Cantidad*',
      'fr': 'Montant*',
      'tl': 'Halaga*',
      'zh_Hans': '数量*',
    },
    'xlqsqmp9': {
      'en': '0.00',
      'es': '0.00',
      'fr': '0,00',
      'tl': '0.00',
      'zh_Hans': '0.00',
    },
    'o1cso2hp': {
      'en': 'Description*',
      'es': 'Descripción*',
      'fr': 'Description*',
      'tl': 'Paglalarawan*',
      'zh_Hans': '描述*',
    },
    'r79yylov': {
      'en': 'Category',
      'es': 'Categoría',
      'fr': 'Catégorie',
      'tl': 'Kategorya',
      'zh_Hans': '类别',
    },
    'qjletz0c': {
      'en': 'Tags',
      'es': 'Etiquetas',
      'fr': 'Mots clés',
      'tl': 'Mga tag',
      'zh_Hans': '标签',
    },
    '975z1mda': {
      'en': 'Comma Separated List',
      'es': 'Lista separada por comas',
      'fr': 'Liste séparée par des virgules',
      'tl': 'Listahan ng Comma Separated',
      'zh_Hans': '逗号分隔列表',
    },
    '59xgdtb8': {
      'en': 'Cleared?                                                 ',
      'es': '¿Aclarado?',
      'fr': 'Effacé ?',
      'tl': 'Na-clear?',
      'zh_Hans': '清除了吗？',
    },
    'z8ztxd74': {
      'en': 'Upload Receipt',
      'es': 'Cargar recibo',
      'fr': 'Télécharger le reçu',
      'tl': 'Mag-upload ng Resibo',
      'zh_Hans': '上传收据',
    },
    'v1uh6xgd': {
      'en': 'Add Transaction',
      'es': 'Agregar transacción',
      'fr': 'Ajouter une transaction',
      'tl': 'Magdagdag ng Transaksyon',
      'zh_Hans': '添加交易',
    },
    'hiqjw0eb': {
      'en': 'Add Transaction',
      'es': 'Agregar transacción',
      'fr': 'Ajouter une transaction',
      'tl': 'Magdagdag ng Transaksyon',
      'zh_Hans': '添加交易',
    },
    'axa67esb': {
      'en': 'Transaction',
      'es': 'Transacción',
      'fr': 'Transaction',
      'tl': 'Transaksyon',
      'zh_Hans': '交易',
    },
  },
  // EditUser
  {
    '648tohc5': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'nnhjo7e1': {
      'en': 'Phone Number',
      'es': 'Número de teléfono',
      'fr': 'Numéro de téléphone',
      'tl': 'Numero ng telepono',
      'zh_Hans': '电话号码',
    },
    'yp5imn4x': {
      'en': 'Update Profile',
      'es': 'Actualización del perfil',
      'fr': 'Mettre à jour le profil',
      'tl': 'I-update ang Profile',
      'zh_Hans': '更新个人信息',
    },
    'ihlfs3p2': {
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'tl': 'Ibahin ang profile',
      'zh_Hans': '编辑个人资料',
    },
    '1nhlwor7': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // EditMembers
  {
    'f5ymmlet': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'h0n074ig': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '6asprp4e': {
      'en': 'Select Household',
      'es': 'Seleccione Hogar',
      'fr': 'Sélectionnez le foyer',
      'tl': 'Piliin ang Sambahayan',
      'zh_Hans': '选择家庭',
    },
    'z1mwdnyl': {
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'tl': 'Pangalan',
      'zh_Hans': '姓名',
    },
    'pmu5ve7d': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'tl': 'Email',
      'zh_Hans': '电子邮件',
    },
    'h3h76udw': {
      'en': 'Joined',
      'es': 'Unido',
      'fr': 'Rejoint',
      'tl': 'Sumali',
      'zh_Hans': '已加入',
    },
    'mzwo7etp': {
      'en': 'Action',
      'es': 'Acción',
      'fr': 'Action',
      'tl': 'Aksyon',
      'zh_Hans': '行动',
    },
    'yd5206xw': {
      'en': 'Edit Members',
      'es': 'Editar miembros',
      'fr': 'Modifier les membres',
      'tl': 'I-edit ang mga Miyembro',
      'zh_Hans': '編輯成員',
    },
    'uopp4d42': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Ledger
  {
    'fi6ceitj': {
      'en': 'example',
      'es': 'ejemplo',
      'fr': 'exemple',
      'tl': 'halimbawa',
      'zh_Hans': '例子',
    },
    '8rb6mvvv': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'teylsa79': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'oadh8i46': {
      'en': 'Select Household',
      'es': 'Seleccione Hogar',
      'fr': 'Sélectionnez le foyer',
      'tl': 'Piliin ang Sambahayan',
      'zh_Hans': '选择家庭',
    },
    'rcl2s0p2': {
      'en': 'View Spending Habits',
      'es': 'Ver hábitos de gasto',
      'fr': 'Afficher les habitudes de dépenses',
      'tl': 'Tingnan ang mga Gawi sa Paggastos',
      'zh_Hans': '查看消费习惯',
    },
    't9s92rrf': {
      'en': 'Total Spent This month: ',
      'es': 'Total gastado este mes:',
      'fr': 'Total dépensé ce mois-ci :',
      'tl': 'Kabuuang Ginastos Ngayong buwan:',
      'zh_Hans': '本月总支出：',
    },
    'lxij45w4': {
      'en': 'Safe To Spend: ',
      'es': 'Seguro para gastar:',
      'fr': 'Dépenser en toute sécurité :',
      'tl': 'Ligtas na Gastusin:',
      'zh_Hans': '安全消费：',
    },
    '37wyhkz3': {
      'en': 'Ledger',
      'es': 'Libro mayor',
      'fr': 'registre',
      'tl': 'Ledger',
      'zh_Hans': '总帐',
    },
    'z67rchgz': {
      'en': 'Ledger',
      'es': 'Libro mayor',
      'fr': 'registre',
      'tl': 'Ledger',
      'zh_Hans': '总帐',
    },
  },
  // Settings
  {
    'dqng4nv7': {
      'en': 'Change Email / Phone number',
      'es': 'Cambiar correo electrónico/número de teléfono',
      'fr': 'Changer l\'e-mail / le numéro de téléphone',
      'tl': 'Baguhin ang Email / Numero ng Telepono',
      'zh_Hans': '更改电子邮箱 / 电话号码',
    },
    'urvy98o6': {
      'en': 'Add Household',
      'es': 'Agregar hogar',
      'fr': 'Ajouter un foyer',
      'tl': 'Magdagdag ng Sambahayan',
      'zh_Hans': '添加家庭',
    },
    'gr5tzrtt': {
      'en': 'Invitations',
      'es': 'Invitaciones',
      'fr': 'Invitations',
      'tl': 'Mga imbitasyon',
      'zh_Hans': '邀请',
    },
    'vki2yai0': {
      'en': 'Edit Members',
      'es': 'Editar miembros',
      'fr': 'Modifier les membres',
      'tl': 'I-edit ang mga Miyembro',
      'zh_Hans': '編輯成員',
    },
    'b61v90ua': {
      'en': 'Wallet',
      'es': 'Billetera',
      'fr': 'Portefeuille',
      'tl': 'Wallet',
      'zh_Hans': '钱包',
    },
    'kewqnqb6': {
      'en': 'Notifications',
      'es': 'Notificaciones',
      'fr': 'Notifications',
      'tl': 'Mga abiso',
      'zh_Hans': '通知',
    },
    'r8wk2rgp': {
      'en': 'Light Mode',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'tl': 'Light Mode',
      'zh_Hans': '灯光模式',
    },
    'd6ph9sip': {
      'en': 'Dark Mode',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'tl': 'Dark Mode',
      'zh_Hans': '暗黑模式',
    },
    'old6drlr': {
      'en': 'Settings',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'tl': 'Mga setting',
      'zh_Hans': '设置',
    },
    '9lph6yzp': {
      'en': 'Settings',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'tl': 'Mga setting',
      'zh_Hans': '设置',
    },
  },
  // Incomes
  {
    '8hecepyl': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'm95pe4l2': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'fqglnn4b': {
      'en': 'Your Incomes',
      'es': 'Tus ingresos',
      'fr': 'Vos revenus',
      'tl': 'Iyong Mga Kita',
      'zh_Hans': '您的收入',
    },
    'mye01jkr': {
      'en': 'Below is a list of your Incomes for the month',
      'es': 'A continuación se muestra una lista de sus ingresos del mes.',
      'fr': 'Vous trouverez ci-dessous une liste de vos revenus pour le mois',
      'tl': 'Nasa ibaba ang isang listahan ng iyong mga Kita para sa buwan',
      'zh_Hans': '以下是您本月的收入清单',
    },
    '2msslbpg': {
      'en': 'Acme Inc',
      'es': 'acme inc.',
      'fr': 'Acmé Inc',
      'tl': 'Acme Inc',
      'zh_Hans': 'Acme 公司',
    },
    'wolvdukh': {
      'en': 'Total ',
      'es': 'Total',
      'fr': 'Total',
      'tl': 'Kabuuan',
      'zh_Hans': '全部的',
    },
    '07gqawdr': {
      'en': 'Next Payday ',
      'es': 'Próximo día de pago',
      'fr': 'Prochain jour de paie',
      'tl': 'Susunod na Payday',
      'zh_Hans': '下一个发薪日',
    },
    '5huamn5b': {
      'en': 'Incomes',
      'es': 'Ingresos',
      'fr': 'Revenus',
      'tl': 'Mga kita',
      'zh_Hans': '收入',
    },
    'xkkd5m13': {
      'en': 'Incomes ',
      'es': 'Ingresos',
      'fr': 'Revenus',
      'tl': 'Mga kita',
      'zh_Hans': '收入',
    },
  },
  // PaymentSources
  {
    'eg33hesr': {
      'en': 'example',
      'es': 'ejemplo',
      'fr': 'exemple',
      'tl': 'halimbawa',
      'zh_Hans': '例子',
    },
    'gsemlu16': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    '3a1ra9an': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'dk9jnu6h': {
      'en': 'Select Household',
      'es': 'Seleccione Hogar',
      'fr': 'Sélectionnez le foyer',
      'tl': 'Piliin ang Sambahayan',
      'zh_Hans': '选择家庭',
    },
    'thnemytb': {
      'en': 'Wallet',
      'es': 'Billetera',
      'fr': 'Portefeuille',
      'tl': 'Wallet',
      'zh_Hans': '钱包',
    },
    'ka2j9ssj': {
      'en': 'Wallet',
      'es': 'Billetera',
      'fr': 'Portefeuille',
      'tl': 'Wallet',
      'zh_Hans': '钱包',
    },
  },
  // Export
  {
    'zreuhkb1': {
      'en': 'Export',
      'es': 'Exportar',
      'fr': 'Exporter',
      'tl': 'I-export',
      'zh_Hans': '出口',
    },
    '5159rhj6': {
      'en': 'Reports',
      'es': 'Informes',
      'fr': 'Rapports',
      'tl': 'Mga ulat',
      'zh_Hans': '报告',
    },
  },
  // Bills
  {
    'hxb5ji1p': {
      'en': 'example',
      'es': 'ejemplo',
      'fr': 'exemple',
      'tl': 'halimbawa',
      'zh_Hans': '例子',
    },
    '2oqt8a86': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'qij3am63': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'umkrgsf1': {
      'en': 'Select Household',
      'es': 'Seleccione Hogar',
      'fr': 'Sélectionnez le foyer',
      'tl': 'Piliin ang Sambahayan',
      'zh_Hans': '选择家庭',
    },
    'frr71lhz': {
      'en': 'Due',
      'es': 'Pendiente',
      'fr': 'Exigible',
      'tl': 'Dahil',
      'zh_Hans': '到期的',
    },
    'ov331tcb': {
      'en': 'DUE',
      'es': 'PENDIENTE',
      'fr': 'EXIGIBLE',
      'tl': 'DUE',
      'zh_Hans': '到期的',
    },
    'c3j9yic1': {
      'en': 'PAST DUE',
      'es': 'VENCIDO',
      'fr': 'EN RETARD',
      'tl': 'NAKARAAN NA',
      'zh_Hans': '逾期',
    },
    '02zggwa4': {
      'en': 'Paid',
      'es': 'Pagado',
      'fr': 'Payé',
      'tl': 'Binayaran',
      'zh_Hans': '有薪酬的',
    },
    '2k2k7vfa': {
      'en': 'PAID',
      'es': 'PAGADO',
      'fr': 'PAYÉ',
      'tl': 'BINAYARAN',
      'zh_Hans': '有薪酬的',
    },
    'dyrxz4j4': {
      'en': 'Future',
      'es': 'Futuro',
      'fr': 'Avenir',
      'tl': 'Kinabukasan',
      'zh_Hans': '未来',
    },
    'm5iyw6s4': {
      'en': 'Not Due Yet',
      'es': 'Aún no vencido',
      'fr': 'Pas encore dû',
      'tl': 'Hindi Pa Due',
      'zh_Hans': '尚未到期',
    },
    '0kyl2p6o': {
      'en': 'Bills',
      'es': 'Facturas',
      'fr': 'Factures',
      'tl': 'Mga perang papel',
      'zh_Hans': '法案',
    },
    'ttmje8k7': {
      'en': 'Bills',
      'es': 'Facturas',
      'fr': 'Factures',
      'tl': 'Mga perang papel',
      'zh_Hans': '法案',
    },
  },
  // BillDetails
  {
    'cpk51b2m': {
      'en': 'Name: ',
      'es': 'Nombre:',
      'fr': 'Nom:',
      'tl': 'Pangalan:',
      'zh_Hans': '姓名：',
    },
    'ep6wk3k5': {
      'en': 'Amount: ',
      'es': 'Cantidad:',
      'fr': 'Montant:',
      'tl': 'Halaga:',
      'zh_Hans': '数量：',
    },
    'e2p8a4bg': {
      'en': 'Frequency: ',
      'es': 'Frecuencia:',
      'fr': 'Fréquence:',
      'tl': 'Dalas:',
      'zh_Hans': '频率：',
    },
    '0nxsi21t': {
      'en': 'Category: ',
      'es': 'Categoría:',
      'fr': 'Catégorie:',
      'tl': 'Kategorya:',
      'zh_Hans': '类别：',
    },
    '58jmo294': {
      'en': 'Description: ',
      'es': 'Descripción:',
      'fr': 'Description:',
      'tl': 'Paglalarawan:',
      'zh_Hans': '描述：',
    },
    '75qcqdik': {
      'en': 'Day of the Month Due: ',
      'es': 'Día del mes de vencimiento:',
      'fr': 'Jour du mois dû :',
      'tl': 'Araw ng Buwan na Nakatakda:',
      'zh_Hans': '每月到期日：',
    },
    'nb89soq9': {
      'en': 'Status: ',
      'es': 'Estado:',
      'fr': 'Statut:',
      'tl': 'Katayuan:',
      'zh_Hans': '地位：',
    },
    'ok0j6grh': {
      'en': 'Created At: ',
      'es': 'Creado en:',
      'fr': 'Créé à:',
      'tl': 'Nilikha Sa:',
      'zh_Hans': '创建时间：',
    },
    '8ooplkwr': {
      'en': 'Login Details',
      'es': 'detalles de registro',
      'fr': 'détails de connexion',
      'tl': 'Mga Detalye sa Pag-login',
      'zh_Hans': '登录详细信息',
    },
    'j96w6oru': {
      'en': 'Biller Website: ',
      'es': 'Sitio web del facturador:',
      'fr': 'Site Web du émetteur de factures :',
      'tl': 'Website ng Biller:',
      'zh_Hans': '比勒网站：',
    },
    'vvgav8lp': {
      'en': 'Username: ',
      'es': 'Nombre de usuario:',
      'fr': 'Nom d\'utilisateur:',
      'tl': 'Username:',
      'zh_Hans': '用户名：',
    },
    '8v2mv767': {
      'en': 'Password: ',
      'es': 'Contraseña:',
      'fr': 'Mot de passe:',
      'tl': 'Password:',
      'zh_Hans': '密码：',
    },
    'ncn4awxv': {
      'en': '********************',
      'es': '**********************',
      'fr': '********************',
      'tl': '******************',
      'zh_Hans': '********************',
    },
    'bxcf6zx0': {
      'en': 'Username and Password Stored Securely',
      'es': 'Nombre de usuario y contraseña almacenados de forma segura',
      'fr': 'Nom d\'utilisateur et mot de passe stockés en toute sécurité',
      'tl': 'Ang Username at Password ay Ligtas na Nakaimbak',
      'zh_Hans': '用户名和密码安全存储',
    },
    'vjp9wzjv': {
      'en': 'Bill Details',
      'es': 'Detalles de la factura',
      'fr': 'Détails de la facture',
      'tl': 'Mga Detalye ng Bill',
      'zh_Hans': '账单详情',
    },
    'qr8b8pmj': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // TransactionDetails
  {
    't2urdtuo': {
      'en': 'Transaction Details',
      'es': 'Detalles de la transacción',
      'fr': 'détails de la transaction',
      'tl': 'Mga Detalye ng Transaksyon',
      'zh_Hans': '交易明细',
    },
    '6z25bdwi': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    '8ihgnfl6': {
      'en': 'Amount',
      'es': 'Cantidad',
      'fr': 'Montant',
      'tl': 'Halaga',
      'zh_Hans': '数量',
    },
    'lvgz9n0f': {
      'en': 'Cleared?',
      'es': '¿Aclarado?',
      'fr': 'Effacé ?',
      'tl': 'Na-clear?',
      'zh_Hans': '清除了吗？',
    },
    'ovi6bo69': {
      'en': 'TransactionDate',
      'es': 'Fecha de Transacción',
      'fr': 'Date de la transaction',
      'tl': 'Petsa ng transaksyon',
      'zh_Hans': '交易日期',
    },
    '0wqdvzy3': {
      'en': 'Created At',
      'es': 'Creado en',
      'fr': 'Créé à',
      'tl': 'Nilikha Sa',
      'zh_Hans': '创建于',
    },
    'dmcmufu1': {
      'en': 'Updated At',
      'es': 'Actualizado en',
      'fr': 'Mis à jour à',
      'tl': 'Nai-update Sa',
      'zh_Hans': '更新于',
    },
    '96155r76': {
      'en': 'Transaction Type',
      'es': 'tipo de transacción',
      'fr': 'Type de transaction',
      'tl': 'Uri ng Transaksyon',
      'zh_Hans': '交易类型',
    },
    'pwgfruwk': {
      'en': 'Category',
      'es': 'Categoría',
      'fr': 'Catégorie',
      'tl': 'Kategorya',
      'zh_Hans': '类别',
    },
    'p9surem7': {
      'en': 'Updated By',
      'es': 'Actualizado por',
      'fr': 'Mis à jour par',
      'tl': 'Na-update Ni',
      'zh_Hans': '更新者',
    },
    'l15uojq6': {
      'en': 'Tags',
      'es': 'Etiquetas',
      'fr': 'Mots clés',
      'tl': 'Mga tag',
      'zh_Hans': '标签',
    },
    'f60bc50b': {
      'en': 'Payment Source Details',
      'es': 'Detalles de la fuente de pago',
      'fr': 'Détails de la source de paiement',
      'tl': 'Mga Detalye ng Pinagmulan ng Pagbabayad',
      'zh_Hans': '付款来源详情',
    },
    'e5658oi2': {
      'en': 'Payment Source',
      'es': 'Fuente de pago',
      'fr': 'Source de paiement',
      'tl': 'Pinagmulan ng Pagbabayad',
      'zh_Hans': '付款来源',
    },
    'gyvr51yd': {
      'en': 'Running Total',
      'es': 'Total acumulado',
      'fr': 'Total cumulé',
      'tl': 'Running Total',
      'zh_Hans': '累计',
    },
    'pjqyp5lk': {
      'en': 'Payment Type',
      'es': 'Tipo de pago',
      'fr': 'Type de paiement',
      'tl': 'Uri ng Pagbabayad',
      'zh_Hans': '付款方式',
    },
    '36170s1s': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    'qd6hqt9e': {
      'en': 'Created At',
      'es': 'Creado en',
      'fr': 'Créé à',
      'tl': 'Nilikha Sa',
      'zh_Hans': '创建于',
    },
    'ki3664fv': {
      'en': 'Updated At',
      'es': 'Actualizado en',
      'fr': 'Mis à jour à',
      'tl': 'Nai-update Sa',
      'zh_Hans': '更新于',
    },
    '46nxfr7m': {
      'en': 'Transaction Details',
      'es': 'Detalles de la transacción',
      'fr': 'détails de la transaction',
      'tl': 'Mga Detalye ng Transaksyon',
      'zh_Hans': '交易明细',
    },
    'm8c2hfnm': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // IncomeDetails
  {
    'n7s2rlty': {
      'en': 'Income Details',
      'es': 'Detalles de ingresos',
      'fr': 'Détails du revenu',
      'tl': 'Mga Detalye ng Kita',
      'zh_Hans': '收入详情',
    },
    'hq2rzsun': {
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'tl': 'Pangalan',
      'zh_Hans': '姓名',
    },
    '1gzga15u': {
      'en': 'Amount',
      'es': 'Cantidad',
      'fr': 'Montant',
      'tl': 'Halaga',
      'zh_Hans': '数量',
    },
    '6olynats': {
      'en': 'First Payday',
      'es': 'primer día de pago',
      'fr': 'Premier jour de paie',
      'tl': 'Unang Payday',
      'zh_Hans': '第一个发薪日',
    },
    'vmmh318c': {
      'en': 'Frequency',
      'es': 'Frecuencia',
      'fr': 'Fréquence',
      'tl': 'Dalas',
      'zh_Hans': '频率',
    },
    'oesdwhvr': {
      'en': 'Created At',
      'es': 'Creado en',
      'fr': 'Créé à',
      'tl': 'Nilikha Sa',
      'zh_Hans': '创建于',
    },
    'd56uzuns': {
      'en': 'Updated At',
      'es': 'Actualizado en',
      'fr': 'Mis à jour à',
      'tl': 'Nai-update Sa',
      'zh_Hans': '更新于',
    },
    'a13honax': {
      'en': 'Household',
      'es': 'Familiar',
      'fr': 'Ménage',
      'tl': 'Sambahayan',
      'zh_Hans': '家庭',
    },
    's4jxjqy1': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // AddIncome
  {
    'we9ipn6g': {
      'en': 'Income Name',
      'es': 'Nombre de ingresos',
      'fr': 'Nom du revenu',
      'tl': 'Pangalan ng Kita',
      'zh_Hans': '收入名称',
    },
    'rc7sf4xp': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    'zx7xm0en': {
      'en': 'Amount',
      'es': 'Cantidad',
      'fr': 'Montant',
      'tl': 'Halaga',
      'zh_Hans': '数量',
    },
    'oull17fa': {
      'en': 'One Time',
      'es': 'Una vez',
      'fr': 'Une fois',
      'tl': 'Isang beses',
      'zh_Hans': '一度',
    },
    '7dqsax74': {
      'en': 'Weekly',
      'es': 'Semanalmente',
      'fr': 'Hebdomadaire',
      'tl': 'Lingguhan',
      'zh_Hans': '每周',
    },
    'xfu2ef6o': {
      'en': 'Bi-Weekly - Every 2 weeks',
      'es': 'Quincenal: cada 2 semanas',
      'fr': 'Bi-hebdomadaire - Toutes les 2 semaines',
      'tl': 'Bi-Weekly - Bawat 2 linggo',
      'zh_Hans': '每两周 - 每两周',
    },
    'ntv407h2': {
      'en': 'Monthly - Every 30 days',
      'es': 'Mensual - Cada 30 días',
      'fr': 'Mensuel - Tous les 30 jours',
      'tl': 'Buwan-buwan - Bawat 30 araw',
      'zh_Hans': '每月 - 每 30 天',
    },
    'uvx33bbo': {
      'en': 'Bi-Monthly - Every 60 days',
      'es': 'Bimensual - Cada 60 días',
      'fr': 'Bimensuel - Tous les 60 jours',
      'tl': 'Bi-Buwanang - Bawat 60 araw',
      'zh_Hans': '每两个月 - 每 60 天',
    },
    '7x3iamd7': {
      'en': 'Quarterly - Every 90 days',
      'es': 'Trimestral - Cada 90 días',
      'fr': 'Trimestriel - Tous les 90 jours',
      'tl': 'Quarterly - Bawat 90 araw',
      'zh_Hans': '每季度 - 每 90 天',
    },
    'd0jf1td8': {
      'en': 'Annually',
      'es': 'Anualmente',
      'fr': 'Annuellement',
      'tl': 'Taun-taon',
      'zh_Hans': '每年',
    },
    'xlitdyv6': {
      'en': 'How Often Do You Get Paid?',
      'es': '¿Con qué frecuencia le pagan?',
      'fr': 'À quelle fréquence recevez-vous votre salaire?',
      'tl': 'Gaano Ka kadalas Nababayaran?',
      'zh_Hans': '您多久领一次工资？',
    },
    'y2owf7ix': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'fae4ldn2': {
      'en': 'One Time',
      'es': 'Una vez',
      'fr': 'Une fois',
      'tl': 'Isang beses',
      'zh_Hans': '一度',
    },
    'j8xwab89': {
      'en': 'Weekly',
      'es': 'Semanalmente',
      'fr': 'Hebdomadaire',
      'tl': 'Lingguhan',
      'zh_Hans': '每周',
    },
    'ci0498nk': {
      'en': 'Bi-Weekly - Every 2 weeks',
      'es': 'Quincenal: cada 2 semanas',
      'fr': 'Bi-hebdomadaire - Toutes les 2 semaines',
      'tl': 'Bi-Weekly - Bawat 2 linggo',
      'zh_Hans': '每两周 - 每两周',
    },
    'btu2rhai': {
      'en': 'Monthly - Every 30 days',
      'es': 'Mensual - Cada 30 días',
      'fr': 'Mensuel - Tous les 30 jours',
      'tl': 'Buwan-buwan - Bawat 30 araw',
      'zh_Hans': '每月 - 每 30 天',
    },
    't5dv4hse': {
      'en': 'Bi-Monthly - Every 60 days',
      'es': 'Bimensual - Cada 60 días',
      'fr': 'Bimensuel - Tous les 60 jours',
      'tl': 'Bi-Buwanang - Bawat 60 araw',
      'zh_Hans': '每两个月 - 每 60 天',
    },
    '4avz4wz8': {
      'en': 'Quarterly - Every 90 days',
      'es': 'Trimestral - Cada 90 días',
      'fr': 'Trimestriel - Tous les 90 jours',
      'tl': 'Quarterly - Bawat 90 araw',
      'zh_Hans': '每季度 - 每 90 天',
    },
    'hrw5syxr': {
      'en': 'Annually',
      'es': 'Anualmente',
      'fr': 'Annuellement',
      'tl': 'Taun-taon',
      'zh_Hans': '每年',
    },
    'kb9e4o15': {
      'en': 'Connect To Payment Source',
      'es': 'Conectarse a la fuente de pago',
      'fr': 'Connectez-vous à la source de paiement',
      'tl': 'Kumonekta sa Pinagmulan ng Pagbabayad',
      'zh_Hans': '连接到付款来源',
    },
    '6gslvggc': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'uzkzq8av': {
      'en': 'Add Income',
      'es': 'Agregar ingresos',
      'fr': 'Ajouter un revenu',
      'tl': 'Magdagdag ng Kita',
      'zh_Hans': '添加收入',
    },
    'wrua2ny7': {
      'en': 'Add Income',
      'es': 'Agregar ingresos',
      'fr': 'Ajouter un revenu',
      'tl': 'Magdagdag ng Kita',
      'zh_Hans': '添加收入',
    },
    '0qp21nl4': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Notifications
  {
    'of9s4gmg': {
      'en': 'Notifications',
      'es': 'Notificaciones',
      'fr': 'Notifications',
      'tl': 'Mga abiso',
      'zh_Hans': '通知',
    },
    'diwgwdua': {
      'en': 'Email Address: ',
      'es': 'Dirección de correo electrónico:',
      'fr': 'Adresse e-mail:',
      'tl': 'Email Address:',
      'zh_Hans': '电子邮件地址：',
    },
    'efx2ixfe': {
      'en': 'Title: ',
      'es': 'Título:',
      'fr': 'Titre:',
      'tl': 'Pamagat:',
      'zh_Hans': '标题：',
    },
    '9lj2cyo7': {
      'en': 'Message: ',
      'es': 'Mensaje:',
      'fr': 'Message:',
      'tl': 'Mensahe:',
      'zh_Hans': '信息：',
    },
    's1wo1npo': {
      'en': 'Created At: ',
      'es': 'Creado en:',
      'fr': 'Créé à:',
      'tl': 'Nilikha Sa:',
      'zh_Hans': '创建时间：',
    },
    'trq7cbq6': {
      'en': 'Updated At:',
      'es': 'Actualizado en:',
      'fr': 'Mis à jour à :',
      'tl': 'Na-update Sa:',
      'zh_Hans': '更新时间：',
    },
    '3pr7hfv2': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Categories
  {
    'e9eu270c': {
      'en': 'January',
      'es': 'Enero',
      'fr': 'Janvier',
      'tl': 'Enero',
      'zh_Hans': '一月',
    },
    '9bdewwbe': {
      'en': 'Februrary',
      'es': 'febrero',
      'fr': 'Février',
      'tl': 'Pebrero',
      'zh_Hans': '二月',
    },
    'gy1rhgxl': {
      'en': 'March',
      'es': 'Marzo',
      'fr': 'Mars',
      'tl': 'Marso',
      'zh_Hans': '行进',
    },
    'b8sg7tgb': {
      'en': 'April',
      'es': 'Abril',
      'fr': 'Avril',
      'tl': 'Abril',
      'zh_Hans': '四月',
    },
    'f75vgn1f': {
      'en': 'May',
      'es': 'Puede',
      'fr': 'Peut',
      'tl': 'May',
      'zh_Hans': '可能',
    },
    'iwrmgggz': {
      'en': 'June',
      'es': 'Junio',
      'fr': 'Juin',
      'tl': 'Hunyo',
      'zh_Hans': '六月',
    },
    'dhrwqosw': {
      'en': 'July',
      'es': 'Julio',
      'fr': 'Juillet',
      'tl': 'Hulyo',
      'zh_Hans': '七月',
    },
    'hk82cqkj': {
      'en': 'August',
      'es': 'Agosto',
      'fr': 'Août',
      'tl': 'Agosto',
      'zh_Hans': '八月',
    },
    '0tb3bbay': {
      'en': 'September',
      'es': 'Septiembre',
      'fr': 'Septembre',
      'tl': 'Setyembre',
      'zh_Hans': '九月',
    },
    '9rf7m25d': {
      'en': 'October',
      'es': 'Octubre',
      'fr': 'Octobre',
      'tl': 'Oktubre',
      'zh_Hans': '十月',
    },
    't6ai1k39': {
      'en': 'November',
      'es': 'Noviembre',
      'fr': 'Novembre',
      'tl': 'Nobyembre',
      'zh_Hans': '十一月',
    },
    'lnxo85uk': {
      'en': 'December',
      'es': 'Diciembre',
      'fr': 'Décembre',
      'tl': 'Disyembre',
      'zh_Hans': '十二月',
    },
    'eecap8j6': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'byyicnyz': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'pu1dfiba': {
      'en': 'Month',
      'es': 'Mes',
      'fr': 'Mois',
      'tl': 'buwan',
      'zh_Hans': '月',
    },
    'ifg1y9a9': {
      'en': '2024',
      'es': '2024',
      'fr': '2024',
      'tl': '2024',
      'zh_Hans': '2024',
    },
    'v97s6izf': {
      'en': '2025',
      'es': '2025',
      'fr': '2025',
      'tl': '2025',
      'zh_Hans': '2025',
    },
    'q901mejj': {
      'en': '2026',
      'es': '2026',
      'fr': '2026',
      'tl': '2026',
      'zh_Hans': '2026',
    },
    'n5d877pr': {
      'en': '2027',
      'es': '2027',
      'fr': '2027',
      'tl': '2027',
      'zh_Hans': '2027',
    },
    'tbtxnlfl': {
      'en': '2028',
      'es': '2028',
      'fr': '2028',
      'tl': '2028',
      'zh_Hans': '2028',
    },
    'e3u8blbm': {
      'en': '2029',
      'es': '2029',
      'fr': '2029',
      'tl': '2029',
      'zh_Hans': '2029',
    },
    '763vnuio': {
      'en': '2030',
      'es': '2030',
      'fr': '2030',
      'tl': '2030',
      'zh_Hans': '2030',
    },
    '4kke73pn': {
      'en': '2031',
      'es': '2031',
      'fr': '2031',
      'tl': '2031',
      'zh_Hans': '2031',
    },
    '7psf9hai': {
      'en': '2032',
      'es': '2032',
      'fr': '2032',
      'tl': '2032',
      'zh_Hans': '2032',
    },
    'dcqc7tcc': {
      'en': '2033',
      'es': '2033',
      'fr': '2033',
      'tl': '2033',
      'zh_Hans': '2033',
    },
    '1cxslyr5': {
      'en': '2034',
      'es': '2034',
      'fr': '2034',
      'tl': '2034',
      'zh_Hans': '2034',
    },
    'hdbx5ykm': {
      'en': '2035',
      'es': '2035',
      'fr': '2035',
      'tl': '2035',
      'zh_Hans': '2035',
    },
    'npdqj4b2': {
      'en': '2036',
      'es': '2036',
      'fr': '2036',
      'tl': '2036',
      'zh_Hans': '2036',
    },
    'g7v3c6l8': {
      'en': '2037',
      'es': '2037',
      'fr': '2037',
      'tl': '2037',
      'zh_Hans': '2037',
    },
    '2srrcz9j': {
      'en': '2038',
      'es': '2038',
      'fr': '2038',
      'tl': '2038',
      'zh_Hans': '2038',
    },
    '854lwgvc': {
      'en': '2039',
      'es': '2039',
      'fr': '2039',
      'tl': '2039',
      'zh_Hans': '2039',
    },
    '0ub55hrx': {
      'en': '2040',
      'es': '2040',
      'fr': '2040',
      'tl': '2040',
      'zh_Hans': '2040',
    },
    'pj6lmue4': {
      'en': '2041',
      'es': '2041',
      'fr': '2041',
      'tl': '2041',
      'zh_Hans': '2041',
    },
    'k9lw6eo8': {
      'en': '2042',
      'es': '2042',
      'fr': '2042',
      'tl': '2042',
      'zh_Hans': '2042',
    },
    'up7ac3xl': {
      'en': '2043',
      'es': '2043',
      'fr': '2043',
      'tl': '2043',
      'zh_Hans': '2043',
    },
    'kagnn1ku': {
      'en': '2044',
      'es': '2044',
      'fr': '2044',
      'tl': '2044',
      'zh_Hans': '2044',
    },
    '2zdf29ox': {
      'en': '2045',
      'es': '2045',
      'fr': '2045',
      'tl': '2045',
      'zh_Hans': '2045',
    },
    'mtiyqlv2': {
      'en': '2046',
      'es': '2046',
      'fr': '2046',
      'tl': '2046',
      'zh_Hans': '2046',
    },
    'mgb0bg4t': {
      'en': '2047',
      'es': '2047',
      'fr': '2047',
      'tl': '2047',
      'zh_Hans': '2047',
    },
    'bw8ddpjn': {
      'en': '2048',
      'es': '2048',
      'fr': '2048',
      'tl': '2048',
      'zh_Hans': '2048',
    },
    'qfyb1pgh': {
      'en': '2049',
      'es': '2049',
      'fr': '2049',
      'tl': '2049',
      'zh_Hans': '2049',
    },
    'odymvswt': {
      'en': '2050',
      'es': '2050',
      'fr': '2050',
      'tl': '2050',
      'zh_Hans': '2050',
    },
    'bmutklbl': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    '8qvqb7n6': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '90y82496': {
      'en': 'Year',
      'es': 'Año',
      'fr': 'Année',
      'tl': 'taon',
      'zh_Hans': '年',
    },
    'o3s9olcs': {
      'en': 'Month to Date',
      'es': 'Mes hasta la fecha',
      'fr': 'Le mois courant',
      'tl': 'Buwan hanggang Petsa',
      'zh_Hans': '本月至今',
    },
    'xm5m0hay': {
      'en': 'Year to Date',
      'es': 'El año hasta la fecha',
      'fr': 'Année à ce jour',
      'tl': 'Taon hanggang Petsa',
      'zh_Hans': '今年迄今为止',
    },
    '8vcz8tbb': {
      'en': 'Categories',
      'es': 'Categorías',
      'fr': 'Catégories',
      'tl': 'Mga kategorya',
      'zh_Hans': '类别',
    },
    'xgncgens': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // AddBill
  {
    '3dhe25b2': {
      'en': 'Add Bill',
      'es': 'Agregar factura',
      'fr': 'Ajouter une facture',
      'tl': 'Magdagdag ng Bill',
      'zh_Hans': '添加账单',
    },
    'a7ftd4zh': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8jhg2xde': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'h58me0s8': {
      'en': 'Payment Source*',
      'es': 'Fuente de pago*',
      'fr': 'Source de paiement*',
      'tl': 'Pinagmulan ng Pagbabayad*',
      'zh_Hans': '付款来源*',
    },
    '3mw8m97t': {
      'en': 'Name of Bill*',
      'es': 'Nombre de la factura*',
      'fr': 'Nom de la facture*',
      'tl': 'Pangalan ng Bill*',
      'zh_Hans': '账单名称*',
    },
    'iawlktxl': {
      'en': 'Amount*',
      'es': 'Cantidad*',
      'fr': 'Montant*',
      'tl': 'Halaga*',
      'zh_Hans': '数量*',
    },
    '2d2ku081': {
      'en': 'Category',
      'es': 'Categoría',
      'fr': 'Catégorie',
      'tl': 'Kategorya',
      'zh_Hans': '类别',
    },
    'rofbjklk': {
      'en': 'Bill',
      'es': 'Factura',
      'fr': 'Facture',
      'tl': 'Bill',
      'zh_Hans': '账单',
    },
    'sc7asjte': {
      'en': '1st',
      'es': '1er',
      'fr': '1er',
      'tl': '1st',
      'zh_Hans': '第一',
    },
    'm3ffx2q7': {
      'en': '2nd',
      'es': '2do',
      'fr': '2ème',
      'tl': 'ika-2',
      'zh_Hans': '第二',
    },
    'q632u26w': {
      'en': '3rd',
      'es': '3er',
      'fr': '3ème',
      'tl': 'ika-3',
      'zh_Hans': '第三',
    },
    'w5chra2x': {
      'en': '4th',
      'es': '4to',
      'fr': '4ème',
      'tl': 'ika-4',
      'zh_Hans': '第四',
    },
    'zb7x5yk2': {
      'en': '5th',
      'es': '5to',
      'fr': '5ème',
      'tl': 'ika-5',
      'zh_Hans': '第五',
    },
    'mgogy3d2': {
      'en': '6th',
      'es': '6to',
      'fr': '6ème',
      'tl': 'ika-6',
      'zh_Hans': '第六',
    },
    'g5mq3lyr': {
      'en': '7th',
      'es': '7mo',
      'fr': '7ème',
      'tl': 'ika-7',
      'zh_Hans': '第七',
    },
    'huaz5xx9': {
      'en': '8th',
      'es': 'octavo',
      'fr': '8ème',
      'tl': 'ika-8',
      'zh_Hans': '第八',
    },
    'lrp1gt6s': {
      'en': '9th',
      'es': 'noveno',
      'fr': '9ème',
      'tl': 'ika-9',
      'zh_Hans': '第九',
    },
    'lgrykxf2': {
      'en': '10th',
      'es': '10mo',
      'fr': '10ème',
      'tl': 'ika-10',
      'zh_Hans': '第十',
    },
    '242v42vd': {
      'en': '11th',
      'es': '11',
      'fr': '11ème',
      'tl': 'ika-11',
      'zh_Hans': '第11届',
    },
    'lpsagjdo': {
      'en': '12th',
      'es': '12',
      'fr': '12ème',
      'tl': 'ika-12',
      'zh_Hans': '第十二',
    },
    '73uo8uyh': {
      'en': '13th',
      'es': '13',
      'fr': '13ème',
      'tl': 'ika-13',
      'zh_Hans': '第十三',
    },
    'vr9139yi': {
      'en': '14th',
      'es': '14',
      'fr': '14ème',
      'tl': 'ika-14',
      'zh_Hans': '第十四',
    },
    'phemj3qo': {
      'en': '15th',
      'es': '15',
      'fr': '15',
      'tl': 'ika-15',
      'zh_Hans': '第十五',
    },
    's6z57upd': {
      'en': '16th',
      'es': '16',
      'fr': '16ème',
      'tl': 'ika-16',
      'zh_Hans': '第十六',
    },
    'zd5ojm2b': {
      'en': '17th',
      'es': '17',
      'fr': '17ème',
      'tl': 'ika-17',
      'zh_Hans': '第十七',
    },
    'ot39ma9z': {
      'en': '18th',
      'es': '18',
      'fr': '18ème',
      'tl': 'ika-18',
      'zh_Hans': '第十八',
    },
    'dl6b0c2p': {
      'en': '19th',
      'es': '19',
      'fr': '19ème',
      'tl': 'ika-19',
      'zh_Hans': '第十九',
    },
    's7b8uxzd': {
      'en': '20th',
      'es': '20',
      'fr': '20',
      'tl': 'ika-20',
      'zh_Hans': '第二十',
    },
    '4f04vtz3': {
      'en': '21st',
      'es': '21',
      'fr': '21',
      'tl': 'ika-21',
      'zh_Hans': '第 21',
    },
    '6cesc1uv': {
      'en': '22nd',
      'es': '22',
      'fr': '22',
      'tl': 'ika-22',
      'zh_Hans': '第22届',
    },
    '6fuk3ob3': {
      'en': '23rd',
      'es': '23',
      'fr': '23',
      'tl': 'ika-23',
      'zh_Hans': '第23届',
    },
    'vbajqnf9': {
      'en': '24th',
      'es': '24',
      'fr': '24',
      'tl': 'ika-24',
      'zh_Hans': '第24届',
    },
    'tw6z6yty': {
      'en': '25th',
      'es': '25',
      'fr': '25',
      'tl': 'ika-25',
      'zh_Hans': '第25届',
    },
    'w4gozext': {
      'en': '26th',
      'es': '26',
      'fr': '26',
      'tl': 'ika-26',
      'zh_Hans': '第26届',
    },
    'tc1z3ag5': {
      'en': '27th',
      'es': '27',
      'fr': '27',
      'tl': 'ika-27',
      'zh_Hans': '第27届',
    },
    'vbdwxgz1': {
      'en': '28th',
      'es': '28',
      'fr': '28',
      'tl': 'ika-28',
      'zh_Hans': '第28届',
    },
    'o2gvnsby': {
      'en': '29th',
      'es': '29',
      'fr': '29',
      'tl': 'ika-29',
      'zh_Hans': '第29届',
    },
    'xo4aioz8': {
      'en': '30th',
      'es': '30',
      'fr': '30',
      'tl': 'ika-30',
      'zh_Hans': '30日',
    },
    'v39le4y0': {
      'en': '31st',
      'es': '31',
      'fr': '31',
      'tl': 'ika-31',
      'zh_Hans': '第31届',
    },
    'r77k9oce': {
      'en': '1st',
      'es': '1er',
      'fr': '1er',
      'tl': '1st',
      'zh_Hans': '第一',
    },
    'jv67qlbu': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '23t6m2gy': {
      'en': 'Day Of the Month Due*',
      'es': 'Día del mes de vencimiento*',
      'fr': 'Jour du mois dû*',
      'tl': 'Araw ng Buwan na Nakatakda*',
      'zh_Hans': '每月到期日*',
    },
    'w9cubujr': {
      'en': 'Monthly',
      'es': 'Mensual',
      'fr': 'Mensuel',
      'tl': 'Buwan-buwan',
      'zh_Hans': '每月',
    },
    'cmduuiiw': {
      'en': 'Once',
      'es': 'Una vez',
      'fr': 'Une fois',
      'tl': 'minsan',
      'zh_Hans': '一次',
    },
    'xsdjvpdm': {
      'en': 'Weekly',
      'es': 'Semanalmente',
      'fr': 'Hebdomadaire',
      'tl': 'Lingguhan',
      'zh_Hans': '每周',
    },
    'wayigelf': {
      'en': 'Bi-Weekly (Every 2 weeks)',
      'es': 'Quincenal (Cada 2 semanas)',
      'fr': 'Bi-hebdomadaire (toutes les 2 semaines)',
      'tl': 'Bi-Weekly (bawat 2 linggo)',
      'zh_Hans': '每两周一次',
    },
    'vgrera01': {
      'en': 'Monthly (Every 30 days)',
      'es': 'Mensual (Cada 30 días)',
      'fr': 'Mensuel (tous les 30 jours)',
      'tl': 'Buwan-buwan (bawat 30 araw)',
      'zh_Hans': '每月（每 30 天）',
    },
    '5it388a0': {
      'en': 'Bi-Monthly (Every 60 days)',
      'es': 'Bimensual (Cada 60 días)',
      'fr': 'Bimensuel (tous les 60 jours)',
      'tl': 'Bi-Buwanang (bawat 60 araw)',
      'zh_Hans': '每两个月（每 60 天）',
    },
    'lzt56jzr': {
      'en': 'Quarterly (Every 90 days)',
      'es': 'Trimestral (Cada 90 días)',
      'fr': 'Trimestriel (tous les 90 jours)',
      'tl': 'quarterly (bawat 90 araw)',
      'zh_Hans': '每季度（每 90 天）',
    },
    '57b95gqc': {
      'en': 'Annually (Yearly)',
      'es': 'Anualmente (Anual)',
      'fr': 'Annuel (annuel)',
      'tl': 'Taun-taon (Taon-taon)',
      'zh_Hans': '每年（每年）',
    },
    'joh0rz56': {
      'en': 'Frequency',
      'es': 'Frecuencia',
      'fr': 'Fréquence',
      'tl': 'Dalas',
      'zh_Hans': '频率',
    },
    'dsg0cjxx': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'spgzx57p': {
      'en': 'Frequency*',
      'es': 'Frecuencia*',
      'fr': 'Fréquence*',
      'tl': 'Dalas*',
      'zh_Hans': '频率*',
    },
    'woiqap2j': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    'n025alnj': {
      'en': 'Biller URL',
      'es': 'URL del facturador',
      'fr': 'URL de facturation',
      'tl': 'URL ng Biller',
      'zh_Hans': '账单网址',
    },
    'ti9rgtbn': {
      'en': 'Please Provide a link to the biller\'s webpage',
      'es': 'Proporcione un enlace a la página web del facturador.',
      'fr': 'Veuillez fournir un lien vers la page Web du émetteur de factures',
      'tl': 'Mangyaring Magbigay ng link sa webpage ng biller',
      'zh_Hans': '请提供付款人网页的链接',
    },
    'cgjxgxb2': {
      'en': 'Username',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'tl': 'Username',
      'zh_Hans': '用户名',
    },
    'd18r914v': {
      'en': 'Biller Username',
      'es': 'Nombre de usuario del facturador',
      'fr': 'Nom d\'utilisateur du émetteur de factures',
      'tl': 'Username ng Biller',
      'zh_Hans': '收款人用户名',
    },
    'o8oi74cz': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'tl': 'Password',
      'zh_Hans': '密码',
    },
    'r6pi1g0y': {
      'en': 'Biller Password',
      'es': 'Contraseña del facturador',
      'fr': 'Mot de passe du émetteur de factures',
      'tl': 'Password ng Biller',
      'zh_Hans': '付款人密码',
    },
    'lalf0hgl': {
      'en': 'Add Bill',
      'es': 'Agregar factura',
      'fr': 'Ajouter une facture',
      'tl': 'Magdagdag ng Bill',
      'zh_Hans': '添加账单',
    },
    'c3unpp3a': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // PaymentSourceDetails
  {
    '4v6caq3g': {
      'en': 'Wallet Details',
      'es': 'Detalles de la billetera',
      'fr': 'Détails du portefeuille',
      'tl': 'Mga Detalye ng Wallet',
      'zh_Hans': '钱包详情',
    },
    'dw6q7vrm': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // QueryTransactions
  {
    'o9uf9t3v': {
      'en': 'Search',
      'es': 'Buscar',
      'fr': 'Recherche',
      'tl': 'Maghanap',
      'zh_Hans': '搜索',
    },
    'm7hqji8i': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // EditBill
  {
    'wke78qjn': {
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'tl': 'Pangalan',
      'zh_Hans': '姓名',
    },
    's4ok44f5': {
      'en': 'Amount',
      'es': 'Cantidad',
      'fr': 'Montant',
      'tl': 'Halaga',
      'zh_Hans': '数量',
    },
    '99cvlthp': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    '9dc2wx2b': {
      'en': 'Once',
      'es': 'Una vez',
      'fr': 'Une fois',
      'tl': 'minsan',
      'zh_Hans': '一次',
    },
    'l6ho10k9': {
      'en': 'Weekly',
      'es': 'Semanalmente',
      'fr': 'Hebdomadaire',
      'tl': 'Lingguhan',
      'zh_Hans': '每周',
    },
    's9gze5jm': {
      'en': 'Bi-Weekly ( 14 days)',
      'es': 'Quincenal (14 días)',
      'fr': 'Bi-hebdomadaire (14 jours)',
      'tl': 'Bi-Weekly ( 14 na araw)',
      'zh_Hans': '每两周（14 天）',
    },
    'u41h179g': {
      'en': 'Monthly ( 30 days )',
      'es': 'Mensual ( 30 días )',
      'fr': 'Mensuel ( 30 jours )',
      'tl': 'Buwan-buwan ( 30 araw )',
      'zh_Hans': '每月（30 天）',
    },
    'z4le7m7y': {
      'en': 'Bi-Monthly (60 days )',
      'es': 'Bimestral (60 días)',
      'fr': 'Bimensuel (60 jours)',
      'tl': 'Bi-Buwanang (60 araw )',
      'zh_Hans': '每两个月（60天）',
    },
    'gluezox8': {
      'en': 'Quarterly ( 90 days )',
      'es': 'Trimestral ( 90 días )',
      'fr': 'Trimestriel ( 90 jours )',
      'tl': 'quarterly ( 90 araw )',
      'zh_Hans': '每季度（90 天）',
    },
    'ndxdfvjb': {
      'en': 'Annually',
      'es': 'Anualmente',
      'fr': 'Annuellement',
      'tl': 'Taun-taon',
      'zh_Hans': '每年',
    },
    'e01x5dwq': {
      'en': 'Frequency',
      'es': 'Frecuencia',
      'fr': 'Fréquence',
      'tl': 'Dalas',
      'zh_Hans': '频率',
    },
    'v3zqazvc': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '4scucxos': {
      'en': 'Frequency',
      'es': 'Frecuencia',
      'fr': 'Fréquence',
      'tl': 'Dalas',
      'zh_Hans': '频率',
    },
    'gz9z8xxn': {
      'en': 'Category',
      'es': 'Categoría',
      'fr': 'Catégorie',
      'tl': 'Kategorya',
      'zh_Hans': '类别',
    },
    'q8lws8af': {
      'en': '1st',
      'es': '1er',
      'fr': '1er',
      'tl': '1st',
      'zh_Hans': '第一',
    },
    '5vm8pfju': {
      'en': '2nd',
      'es': '2do',
      'fr': '2ème',
      'tl': 'ika-2',
      'zh_Hans': '第二',
    },
    '1mtk8n37': {
      'en': '3rd',
      'es': '3er',
      'fr': '3ème',
      'tl': 'ika-3',
      'zh_Hans': '第三',
    },
    'dbreicht': {
      'en': '4th',
      'es': '4to',
      'fr': '4ème',
      'tl': 'ika-4',
      'zh_Hans': '第四',
    },
    'udwa06b4': {
      'en': '5th',
      'es': '5to',
      'fr': '5ème',
      'tl': 'ika-5',
      'zh_Hans': '第五',
    },
    'fzvoqfgc': {
      'en': '6th',
      'es': '6to',
      'fr': '6ème',
      'tl': 'ika-6',
      'zh_Hans': '第六',
    },
    'guuyfbpg': {
      'en': '7th',
      'es': '7mo',
      'fr': '7ème',
      'tl': 'ika-7',
      'zh_Hans': '第七',
    },
    'hav19war': {
      'en': '8th',
      'es': 'octavo',
      'fr': '8ème',
      'tl': 'ika-8',
      'zh_Hans': '第八',
    },
    'jgj1hq42': {
      'en': '9th',
      'es': 'noveno',
      'fr': '9ème',
      'tl': 'ika-9',
      'zh_Hans': '第九',
    },
    '61h9ilz6': {
      'en': '10th',
      'es': '10mo',
      'fr': '10ème',
      'tl': 'ika-10',
      'zh_Hans': '第十',
    },
    'ivvlqmsi': {
      'en': '11th',
      'es': '11',
      'fr': '11ème',
      'tl': 'ika-11',
      'zh_Hans': '第11届',
    },
    'mnbxlzss': {
      'en': '12th',
      'es': '12',
      'fr': '12ème',
      'tl': 'ika-12',
      'zh_Hans': '第十二',
    },
    'd4szkz4u': {
      'en': '13th',
      'es': '13',
      'fr': '13ème',
      'tl': 'ika-13',
      'zh_Hans': '第十三',
    },
    'xfomp78o': {
      'en': '14th',
      'es': '14',
      'fr': '14ème',
      'tl': 'ika-14',
      'zh_Hans': '第十四',
    },
    'dpm9v930': {
      'en': '15th',
      'es': '15',
      'fr': '15',
      'tl': 'ika-15',
      'zh_Hans': '第十五',
    },
    'ailpt9oe': {
      'en': '16th',
      'es': '16',
      'fr': '16ème',
      'tl': 'ika-16',
      'zh_Hans': '第十六',
    },
    'z2d6s8xe': {
      'en': '17th',
      'es': '17',
      'fr': '17ème',
      'tl': 'ika-17',
      'zh_Hans': '第十七',
    },
    '3tubel1g': {
      'en': '18th',
      'es': '18',
      'fr': '18ème',
      'tl': 'ika-18',
      'zh_Hans': '第十八',
    },
    '7jw5ksuw': {
      'en': '19th',
      'es': '19',
      'fr': '19ème',
      'tl': 'ika-19',
      'zh_Hans': '第十九',
    },
    'vsgn26tn': {
      'en': '20th',
      'es': '20',
      'fr': '20',
      'tl': 'ika-20',
      'zh_Hans': '第二十',
    },
    'g268bxkk': {
      'en': '21st',
      'es': '21',
      'fr': '21',
      'tl': 'ika-21',
      'zh_Hans': '第 21',
    },
    'c24qeah5': {
      'en': '22nd',
      'es': '22',
      'fr': '22',
      'tl': 'ika-22',
      'zh_Hans': '第22届',
    },
    'n1xtjluu': {
      'en': '23rd',
      'es': '23',
      'fr': '23',
      'tl': 'ika-23',
      'zh_Hans': '第23届',
    },
    'g8460jyx': {
      'en': '24th',
      'es': '24',
      'fr': '24',
      'tl': 'ika-24',
      'zh_Hans': '第24届',
    },
    '4kdretsw': {
      'en': '25th',
      'es': '25',
      'fr': '25',
      'tl': 'ika-25',
      'zh_Hans': '第25届',
    },
    'bw1bseyf': {
      'en': '26th',
      'es': '26',
      'fr': '26',
      'tl': 'ika-26',
      'zh_Hans': '第26届',
    },
    '621furi7': {
      'en': '27th',
      'es': '27',
      'fr': '27',
      'tl': 'ika-27',
      'zh_Hans': '第27届',
    },
    'b1cx5x3n': {
      'en': '28th',
      'es': '28',
      'fr': '28',
      'tl': 'ika-28',
      'zh_Hans': '第28届',
    },
    'l105h6pc': {
      'en': '29th',
      'es': '29',
      'fr': '29',
      'tl': 'ika-29',
      'zh_Hans': '第29届',
    },
    'wa1inmfi': {
      'en': '30th',
      'es': '30',
      'fr': '30',
      'tl': 'ika-30',
      'zh_Hans': '30日',
    },
    'sxvqvrmv': {
      'en': '31st',
      'es': '31',
      'fr': '31',
      'tl': 'ika-31',
      'zh_Hans': '第31届',
    },
    '7ozy6rih': {
      'en': 'Day of the Month Due',
      'es': 'Día del mes vencido',
      'fr': 'Jour du mois dû',
      'tl': 'Araw ng Buwan na Nakatakda',
      'zh_Hans': '每月到期日',
    },
    'wobslc6z': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'x3mcb6sk': {
      'en': 'Cleared',
      'es': 'Borrado',
      'fr': 'Effacé',
      'tl': 'Na-clear',
      'zh_Hans': '已清除',
    },
    'gxhbl97w': {
      'en': 'Pending',
      'es': 'Pendiente',
      'fr': 'En attente',
      'tl': 'Nakabinbin',
      'zh_Hans': '待办的',
    },
    'biy9kiog': {
      'en': 'Cleared?',
      'es': '¿Aclarado?',
      'fr': 'Effacé ?',
      'tl': 'Na-clear?',
      'zh_Hans': '清除了吗？',
    },
    'n288og04': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '7ngmjokn': {
      'en': 'Status',
      'es': 'Estado',
      'fr': 'Statut',
      'tl': 'Katayuan',
      'zh_Hans': '地位',
    },
    'yf31nx2n': {
      'en': 'Biller URL',
      'es': 'URL del facturador',
      'fr': 'URL de facturation',
      'tl': 'URL ng Biller',
      'zh_Hans': '账单网址',
    },
    'nm1v0zy5': {
      'en': 'Username',
      'es': 'Nombre de usuario',
      'fr': 'Nom d\'utilisateur',
      'tl': 'Username',
      'zh_Hans': '用户名',
    },
    'vurkmq5b': {
      'en': 'Password',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'tl': 'Password',
      'zh_Hans': '密码',
    },
    'tvr7v8jq': {
      'en': 'Edit Bill',
      'es': 'Editar factura',
      'fr': 'Modifier la facture',
      'tl': 'I-edit ang Bill',
      'zh_Hans': '編輯帳單',
    },
    '0e3oj3yl': {
      'en': 'Edit Bill',
      'es': 'Editar factura',
      'fr': 'Modifier la facture',
      'tl': 'I-edit ang Bill',
      'zh_Hans': '編輯帳單',
    },
    '1s0a9szv': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // EditIncome
  {
    'ddx4wv1b': {
      'en': 'Edit Income',
      'es': 'Editar ingresos',
      'fr': 'Modifier le revenu',
      'tl': 'I-edit ang Kita',
      'zh_Hans': '编辑收入',
    },
    'lw6miq56': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // Threshold
  {
    'stkdp365': {
      'en': 'Threshold',
      'es': 'Límite',
      'fr': 'Seuil',
      'tl': 'Threshold',
      'zh_Hans': '临界点',
    },
    'a6fulzbw': {
      'en': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'tl': 'Opsyon 1',
      'zh_Hans': '选项1',
    },
    'a530epg0': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'o69rvk6o': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '9xqbn850': {
      'en': 'Select Household*',
      'es': 'Seleccione Hogar*',
      'fr': 'Sélectionnez un foyer*',
      'tl': 'Pumili ng Sambahayan*',
      'zh_Hans': '选择家庭*',
    },
    '2cmw9w8r': {
      'en': 'Option 1',
      'es': 'Opción 1',
      'fr': 'Option 1',
      'tl': 'Opsyon 1',
      'zh_Hans': '选项1',
    },
    '4b0kuftc': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'oejvx8o8': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '6clu8e8h': {
      'en': 'Select Wallet*',
      'es': 'Seleccionar Monedero*',
      'fr': 'Sélectionnez un portefeuille*',
      'tl': 'Piliin ang Wallet*',
      'zh_Hans': '选择钱包*',
    },
    'jfaje44c': {
      'en': 'Set Threshold',
      'es': 'Establecer umbral',
      'fr': 'Définir le seuil',
      'tl': 'Itakda ang Threshold',
      'zh_Hans': '设置阈值',
    },
    'bvvp6uaj': {
      'en': 'View Threshold Breakers',
      'es': 'Ver interruptores de umbral',
      'fr': 'Voir les disjoncteurs de seuil',
      'tl': 'Tingnan ang mga Threshold Breaker',
      'zh_Hans': '查看阈值突破者',
    },
    'fmqngmet': {
      'en': 'Description: ',
      'es': 'Descripción:',
      'fr': 'Description:',
      'tl': 'Paglalarawan:',
      'zh_Hans': '描述：',
    },
    '2ovxahhu': {
      'en': 'Date: ',
      'es': 'Fecha:',
      'fr': 'Date:',
      'tl': 'Petsa:',
      'zh_Hans': '日期：',
    },
    'l1btfjn1': {
      'en': 'Amount: ',
      'es': 'Cantidad:',
      'fr': 'Montant:',
      'tl': 'Halaga:',
      'zh_Hans': '数量：',
    },
    'du9pdkqr': {
      'en': 'Running Total: ',
      'es': 'Total acumulado:',
      'fr': 'Total cumulé :',
      'tl': 'Running Total:',
      'zh_Hans': '总计：',
    },
    'odolg6eo': {
      'en': 'Threshold',
      'es': 'Límite',
      'fr': 'Seuil',
      'tl': 'Threshold',
      'zh_Hans': '临界点',
    },
  },
  // EditNotification
  {
    'o1dwevtb': {
      'en': 'Edit Notification',
      'es': 'Editar notificación',
      'fr': 'Modifier la notification',
      'tl': 'I-edit ang Notification',
      'zh_Hans': '编辑通知',
    },
    'lbmvqzmy': {
      'en':
          'Notifications are created by creating a Bill. Bill Notification dates can be added on the Add Bill Page.',
      'es':
          'Las notificaciones se crean creando una factura. Las fechas de notificación de factura se pueden agregar en la página Agregar factura.',
      'fr':
          'Les notifications sont créées en créant une facture. Les dates de notification de facture peuvent être ajoutées sur la page Ajouter une facture.',
      'tl':
          'Ginagawa ang mga notification sa pamamagitan ng paggawa ng Bill. Maaaring idagdag ang mga petsa ng Notification ng Bill sa Add Bill Page.',
      'zh_Hans': '通过创建账单即可创建通知。可以在添加账单页面添加账单通知日期。',
    },
    'tm9hwe4r': {
      'en': 'Title',
      'es': 'Título',
      'fr': 'Titre',
      'tl': 'Pamagat',
      'zh_Hans': '标题',
    },
    '77lr9mnd': {
      'en': 'Message',
      'es': 'Mensaje',
      'fr': 'Message',
      'tl': 'Mensahe',
      'zh_Hans': '信息',
    },
    '0cj57rfs': {
      'en': 'Edit Notification',
      'es': 'Editar notificación',
      'fr': 'Modifier la notification',
      'tl': 'I-edit ang Notification',
      'zh_Hans': '编辑通知',
    },
    '8dl0db1o': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // EditTransaction
  {
    'vqap2xom': {
      'en': 'Amount',
      'es': 'Cantidad',
      'fr': 'Montant',
      'tl': 'Halaga',
      'zh_Hans': '数量',
    },
    'kgwlb32m': {
      'en': 'Transaction Date',
      'es': 'Fecha de Transacción',
      'fr': 'Date de la transaction',
      'tl': 'Petsa ng transaksyon',
      'zh_Hans': '交易日期',
    },
    'bdmuypo4': {
      'en': 'Tags',
      'es': 'Etiquetas',
      'fr': 'Mots clés',
      'tl': 'Mga tag',
      'zh_Hans': '标签',
    },
    'm9j6ef06': {
      'en': 'Comma Separated List',
      'es': 'Lista separada por comas',
      'fr': 'Liste séparée par des virgules',
      'tl': 'Listahan ng Comma Separated',
      'zh_Hans': '逗号分隔列表',
    },
    'brk00jnf': {
      'en': 'Category',
      'es': 'Categoría',
      'fr': 'Catégorie',
      'tl': 'Kategorya',
      'zh_Hans': '类别',
    },
    'l7b2ij55': {
      'en': 'Description',
      'es': 'Descripción',
      'fr': 'Description',
      'tl': 'Paglalarawan',
      'zh_Hans': '描述',
    },
    '8xbwvi7r': {
      'en': 'Transaction Type',
      'es': 'tipo de transacción',
      'fr': 'Type de transaction',
      'tl': 'Uri ng Transaksyon',
      'zh_Hans': '交易类型',
    },
    'neow3l96': {
      'en': 'Add',
      'es': 'Agregar',
      'fr': 'Ajouter',
      'tl': 'Idagdag',
      'zh_Hans': '添加',
    },
    'cxesbr6v': {
      'en': 'Subtract',
      'es': 'Sustraer',
      'fr': 'Soustraire',
      'tl': 'Ibawas',
      'zh_Hans': '减去',
    },
    '2ybb0ce2': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'clfczwux': {
      'en': 'Status',
      'es': 'Estado',
      'fr': 'Statut',
      'tl': 'Katayuan',
      'zh_Hans': '地位',
    },
    'qs0tglvt': {
      'en': 'Cleared',
      'es': 'Borrado',
      'fr': 'Effacé',
      'tl': 'Na-clear',
      'zh_Hans': '已清除',
    },
    '6e3hfm46': {
      'en': 'Pending',
      'es': 'Pendiente',
      'fr': 'En attente',
      'tl': 'Nakabinbin',
      'zh_Hans': '待办的',
    },
    'oki5snjx': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    '1tfkjbhj': {
      'en': 'Wallet',
      'es': 'Billetera',
      'fr': 'Portefeuille',
      'tl': 'Wallet',
      'zh_Hans': '钱包',
    },
    'cbox33xq': {
      'en': 'Cleared',
      'es': 'Borrado',
      'fr': 'Effacé',
      'tl': 'Na-clear',
      'zh_Hans': '已清除',
    },
    '2em135mo': {
      'en': 'Pending',
      'es': 'Pendiente',
      'fr': 'En attente',
      'tl': 'Nakabinbin',
      'zh_Hans': '待办的',
    },
    'qor4umsl': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'mg9frbzs': {
      'en': 'Click Image to edit',
      'es': 'Haga clic en Imagen para editar',
      'fr': 'Cliquez sur l\'image pour la modifier',
      'tl': 'I-click ang Imahe para i-edit',
      'zh_Hans': '点击图片进行编辑',
    },
    '8xhc1ul1': {
      'en': 'Edit Transaction',
      'es': 'Editar transacción',
      'fr': 'Modifier la transaction',
      'tl': 'I-edit ang Transaksyon',
      'zh_Hans': '编辑交易',
    },
    '6g8fqanz': {
      'en': 'Edit Transaction',
      'es': 'Editar transacción',
      'fr': 'Modifier la transaction',
      'tl': 'I-edit ang Transaksyon',
      'zh_Hans': '編輯交易',
    },
    'stlzc6qu': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'tl': 'Bahay',
      'zh_Hans': '家',
    },
  },
  // EditHousehold
  {
    '4vxq1sor': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '37hgvmq8': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // DeleteUser
  {
    'gpco90ko': {
      'en': 'Page Title',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'eu989foe': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // passwordfield
  {
    's9udb7tj': {
      'en': 'New Password',
      'es': 'Nueva contraseña',
      'fr': 'nouveau mot de passe',
      'tl': 'Bagong Password',
      'zh_Hans': '新密码',
    },
    'frcgmghu': {
      'en': '1 capital letter, 1 special character, 1 number, 8 chars',
      'es': '1 letra mayúscula, 1 carácter especial, 1 número, 8 caracteres',
      'fr': '1 lettre majuscule, 1 caractère spécial, 1 chiffre, 8 caractères',
      'tl': '1 malaking titik, 1 espesyal na karakter, 1 numero, 8 karakter',
      'zh_Hans': '1 个大写字母、1 个特殊字符、1 个数字、8 个字符',
    },
  },
  // SearchTransactions
  {
    '9982x6q3': {
      'en': 'Keyword Search',
      'es': 'Búsqueda por palabra clave',
      'fr': 'Recherche par mot clé',
      'tl': 'Paghahanap ng Keyword',
      'zh_Hans': '关键词搜索',
    },
    '05bp02dn': {
      'en': 'Search Everything',
      'es': 'buscar todo',
      'fr': 'Rechercher tout',
      'tl': 'Hanapin Lahat',
      'zh_Hans': '搜索一切',
    },
    '9wvcyc0y': {
      'en': 'Search',
      'es': 'Buscar',
      'fr': 'Recherche',
      'tl': 'Maghanap',
      'zh_Hans': '搜索',
    },
  },
  // Filter
  {
    'lnds6s8r': {
      'en': 'Filter Options',
      'es': 'Opciones de filtro',
      'fr': 'Options de filtrage',
      'tl': 'Mga Opsyon sa Filter',
      'zh_Hans': '筛选选项',
    },
    'ocldaj3l': {
      'en': 'Min Amount',
      'es': 'Cantidad mínima',
      'fr': 'Montant minimum',
      'tl': 'Min na Halaga',
      'zh_Hans': '最低金额',
    },
    '7gd68aub': {
      'en': 'Max Amount',
      'es': 'Cantidad máxima',
      'fr': 'Montant maximum',
      'tl': 'Max na Halaga',
      'zh_Hans': '最大金额',
    },
    'hk22ysw5': {
      'en': 'Search',
      'es': 'Buscar',
      'fr': 'Recherche',
      'tl': 'Maghanap',
      'zh_Hans': '搜索',
    },
    '00235yee': {
      'en': 'Cleared Only',
      'es': 'Solo borrado',
      'fr': 'Effacé uniquement',
      'tl': 'Na-clear Lamang',
      'zh_Hans': '仅清除',
    },
    'jrn120to': {
      'en': 'Current Month Only',
      'es': 'Solo el mes actual',
      'fr': 'Mois en cours uniquement',
      'tl': 'Kasalukuyang Buwan Lamang',
      'zh_Hans': '仅限当前月份',
    },
    '9io7dr53': {
      'en': 'Month',
      'es': 'Mes',
      'fr': 'Mois',
      'tl': 'buwan',
      'zh_Hans': '月',
    },
    'x9g489v3': {
      'en': 'Year',
      'es': 'Año',
      'fr': 'Année',
      'tl': 'taon',
      'zh_Hans': '年',
    },
    'ljlqib9m': {
      'en': '1 Januaary',
      'es': '1 de enero',
      'fr': '1er janvier',
      'tl': '1 Enero',
      'zh_Hans': '1月1日',
    },
    '9gj21wo4': {
      'en': '2 February',
      'es': '2 de febrero',
      'fr': '2 février',
      'tl': '2 Pebrero',
      'zh_Hans': '2 月 2 日',
    },
    'smhodqik': {
      'en': '3 March',
      'es': '3 de marzo',
      'fr': '3 mars',
      'tl': '3 Marso',
      'zh_Hans': '3 月 3 日',
    },
    'whezd4ws': {
      'en': '4 April',
      'es': '4 de abril',
      'fr': '4 avril',
      'tl': '4 Abril',
      'zh_Hans': '4月4日',
    },
    '2zsski3u': {
      'en': '5 May',
      'es': '5 de mayo',
      'fr': '5 mai',
      'tl': '5 Mayo',
      'zh_Hans': '5月5日',
    },
    'r4dtoxr1': {
      'en': '6 June',
      'es': '6 de junio',
      'fr': '6 juin',
      'tl': '6 Hunyo',
      'zh_Hans': '6 月 6 日',
    },
    'zpgruheb': {
      'en': '7 July',
      'es': '7 de julio',
      'fr': '7 juillet',
      'tl': '7 Hulyo',
      'zh_Hans': '7 月 7 日',
    },
    'gax2lpsi': {
      'en': '8 August',
      'es': '8 de agosto',
      'fr': '8 août',
      'tl': '8 Agosto',
      'zh_Hans': '8 八月',
    },
    '4hdopud8': {
      'en': '9 September',
      'es': '9 de septiembre',
      'fr': '9 septembre',
      'tl': '9 Setyembre',
      'zh_Hans': '9月9日',
    },
    'u079zxlb': {
      'en': '10 October',
      'es': '10 de octubre',
      'fr': '10 octobre',
      'tl': '10 Oktubre',
      'zh_Hans': '10 月 10 日',
    },
    'f1qtf7zi': {
      'en': '11 November',
      'es': '11 de noviembre',
      'fr': '11 novembre',
      'tl': '11 Nobyembre',
      'zh_Hans': '11月11日',
    },
    'vm8k4dax': {
      'en': '12 December',
      'es': '12 de diciembre',
      'fr': '12 décembre',
      'tl': '12 Disyembre',
      'zh_Hans': '12 月 12 日',
    },
    'gfyxrxzd': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'm5857s2k': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
    'gmej8zwc': {
      'en': '2024',
      'es': '2024',
      'fr': '2024',
      'tl': '2024',
      'zh_Hans': '2024',
    },
    'lhfdxzcp': {
      'en': '2025',
      'es': '2025',
      'fr': '2025',
      'tl': '2025',
      'zh_Hans': '2025',
    },
    'qikyu60m': {
      'en': '2026',
      'es': '2026',
      'fr': '2026',
      'tl': '2026',
      'zh_Hans': '2026',
    },
    'ycbjduzc': {
      'en': '2027',
      'es': '2027',
      'fr': '2027',
      'tl': '2027',
      'zh_Hans': '2027',
    },
    'ldearaqy': {
      'en': '2028',
      'es': '2028',
      'fr': '2028',
      'tl': '2028',
      'zh_Hans': '2028',
    },
    'h1x6slnz': {
      'en': '2029',
      'es': '2029',
      'fr': '2029',
      'tl': '2029',
      'zh_Hans': '2029',
    },
    'do0qflx6': {
      'en': '2030',
      'es': '2030',
      'fr': '2030',
      'tl': '2030',
      'zh_Hans': '2030',
    },
    '13lm3f23': {
      'en': '2031',
      'es': '2031',
      'fr': '2031',
      'tl': '2031',
      'zh_Hans': '2031',
    },
    'me6ny26p': {
      'en': '2032',
      'es': '2032',
      'fr': '2032',
      'tl': '2032',
      'zh_Hans': '2032',
    },
    '6epc44p7': {
      'en': '2033',
      'es': '2033',
      'fr': '2033',
      'tl': '2033',
      'zh_Hans': '2033',
    },
    'c05i2s1u': {
      'en': '2034',
      'es': '2034',
      'fr': '2034',
      'tl': '2034',
      'zh_Hans': '2034',
    },
    '25hp7iif': {
      'en': '2035',
      'es': '2035',
      'fr': '2035',
      'tl': '2035',
      'zh_Hans': '2035',
    },
    'wba2ow8e': {
      'en': '2036',
      'es': '2036',
      'fr': '2036',
      'tl': '2036',
      'zh_Hans': '2036',
    },
    'ftq89sks': {
      'en': '2037',
      'es': '2037',
      'fr': '2037',
      'tl': '2037',
      'zh_Hans': '2037',
    },
    'yrd1r451': {
      'en': '2038',
      'es': '2038',
      'fr': '2038',
      'tl': '2038',
      'zh_Hans': '2038',
    },
    '4y1mkb8c': {
      'en': '2039',
      'es': '2039',
      'fr': '2039',
      'tl': '2039',
      'zh_Hans': '2039',
    },
    'biqk08s5': {
      'en': '2040',
      'es': '2040',
      'fr': '2040',
      'tl': '2040',
      'zh_Hans': '2040',
    },
    '4iolkd0i': {
      'en': '2041',
      'es': '2041',
      'fr': '2041',
      'tl': '2041',
      'zh_Hans': '2041',
    },
    'il7ar4ba': {
      'en': '2042',
      'es': '2042',
      'fr': '2042',
      'tl': '2042',
      'zh_Hans': '2042',
    },
    '5haclh3b': {
      'en': '2043',
      'es': '2043',
      'fr': '2043',
      'tl': '2043',
      'zh_Hans': '2043',
    },
    '9nk1hrrb': {
      'en': '2044',
      'es': '2044',
      'fr': '2044',
      'tl': '2044',
      'zh_Hans': '2044',
    },
    '97ppqsp6': {
      'en': '2045',
      'es': '2045',
      'fr': '2045',
      'tl': '2045',
      'zh_Hans': '2045',
    },
    'uhszsqd8': {
      'en': '2046',
      'es': '2046',
      'fr': '2046',
      'tl': '2046',
      'zh_Hans': '2046',
    },
    'yg47rckn': {
      'en': '2047',
      'es': '2047',
      'fr': '2047',
      'tl': '2047',
      'zh_Hans': '2047',
    },
    'rrz6ys9z': {
      'en': '2048',
      'es': '2048',
      'fr': '2048',
      'tl': '2048',
      'zh_Hans': '2048',
    },
    'tyz0c65p': {
      'en': '2049',
      'es': '2049',
      'fr': '2049',
      'tl': '2049',
      'zh_Hans': '2049',
    },
    '8g4cpr3m': {
      'en': '2050',
      'es': '2050',
      'fr': '2050',
      'tl': '2050',
      'zh_Hans': '2050',
    },
    'rbuy9zv2': {
      'en': 'Please select...',
      'es': 'Por favor seleccione...',
      'fr': 'Veuillez sélectionner...',
      'tl': 'Pakipili...',
      'zh_Hans': '请选择...',
    },
    'rgalr3kn': {
      'en': 'Search for an item...',
      'es': 'Buscar un artículo...',
      'fr': 'Rechercher un article...',
      'tl': 'Maghanap ng item...',
      'zh_Hans': '搜索商品...',
    },
  },
  // Miscellaneous
  {
    '57fllogz': {
      'en': 'Please provide Camera access so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hqjyswpi': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gqnpf09i': {
      'en': 'Please provide Biometrics access for quicker login',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rrtsqja0': {
      'en': 'Please provide Calendar access for bills',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0jvhuji2': {
      'en': 'Please provide Camera access so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'u9m5mzh6': {
      'en': 'Please provide access to Photo Library so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '55v3srad': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'es8762ji': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qsxzzvc2': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vnwtrchj': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xclnr7ni': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '53up8ruf': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hnr9h57q': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0z1wal53': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'miuzrtvl': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm8locfsf': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'klc8lp4j': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dfsifyux': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '795j3gj6': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wd7x988o': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'khko1hkh': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tumf7sjr': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wcro1mys': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wxjrdbd9': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ft0gisuq': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bdov1cte': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '70czdhee': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'plomdrwt': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q49jhonk': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lagf6jd9': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's1lod96p': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
