import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'es', 'tl', 'fr', 'zh_Hans'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? tlText = '',
    String? frText = '',
    String? zh_HansText = '',
  }) =>
      [enText, esText, tlText, frText, zh_HansText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Login
  {
    'hxiwpwui': {
      'en': 'Create Account',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'exun2xyq': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'unvb2xpi': {
      'en': 'YourName@example.com',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'y5a6love': {
      'en': 'Phone Number',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1wj9h04k': {
      'en': 'Must include country Code (+1 for USA)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7c3ot4wz': {
      'en': 'First Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fly5shpv': {
      'en': 'Last Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vit8m0nm': {
      'en': 'Opt in to pigs and promotions in your email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5tlavdfn': {
      'en': 'Get Started',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o3reyrbh': {
      'en': 'Log In',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qw06jci8': {
      'en': 'Welcome Back',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e2kqv3tf': {
      'en': 'Fill out the information below in order to access your account.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'f6rvgfs7': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'af2n62ur': {
      'en': 'Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'klva35si': {
      'en': 'Sign In',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'i0bf9sho': {
      'en': 'Forgot Password?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dzpfqy54': {
      'en': 'Verify Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lu7sjzp3': {
      'en': 'Disclaimer: The Purple Piggy Bank LLC is not a bank. ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9iag3u40': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // ConfirmEmail
  {
    '2jxqetp7': {
      'en': 'Check your email for a confirmation code and enter it below',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yfq6xx64': {
      'en': 'Email ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'je3ymwzg': {
      'en': 'Confirm Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pff0v29d': {
      'en': 'Confirm Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qsrie90l': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // ForgotPassword
  {
    '8o3c8w94': {
      'en': 'Email Address',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4g9wlh73': {
      'en': 'Send Me A Reset Code',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yvhi0k3e': {
      'en': 'Forgot Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mo5n9cmm': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // PasswordResetCode
  {
    '8lk6slas': {
      'en': 'Check your email for a confirmation code and enter it below',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e3azezwx': {
      'en': 'Email ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gysxne8w': {
      'en': 'New Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g8ki1rg8': {
      'en': 'New Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xlv8tjrt': {
      'en': 'Set New Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'nic9w7r8': {
      'en': 'Reset Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ox6veo0p': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // CreateHousehold
  {
    '28tml14z': {
      'en':
          'At The Purple Piggy Bank, a \"Household\" is a grouping of budgets. \nYou can name it anything you want.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q5a1tx49': {
      'en': 'Household Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's9e7nrfw': {
      'en': 'Create',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qrqf5ejm': {
      'en': 'New Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'n7u54he6': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AddInvite
  {
    'hcezr687': {
      'en': 'Invite other people to join your Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gkhj25dd': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2bwn6o90': {
      'en': 'Send Invitation',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'sr862bzk': {
      'en': 'Invitations',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fe3uvau5': {
      'en': 'Invite',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AcceptInvite
  {
    'sxb2lz9l': {
      'en': 'Create Account',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2jabljnl': {
      'en': 'Let\'s get started by filling out the form below.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hjpdhn03': {
      'en': 'Invitation Code',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2pxecvbu': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tdziz6ej': {
      'en': 'First Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'do882gxg': {
      'en': 'Last Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6bqxoiy7': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wqmswne9': {
      'en': 'Phone Number',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q854splb': {
      'en': 'Must include country Code (+1 for USA)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '02smpn20': {
      'en': 'Opt into getting pigs and promotions in your email inbox!',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '33j66c20': {
      'en': 'Get Started',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'b2876cm5': {
      'en': 'Accept Invite',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6jhoz580': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AddPaymentSource
  {
    'kdis00po': {
      'en':
          'Add a payment source - This is a way to group where money comes from in your budget.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'zqrj2y9j': {
      'en': 'Checking Account',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e52l5u4z': {
      'en': 'Savings Account',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mi5fc5tx': {
      'en': 'Credit Card',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6px80htj': {
      'en': 'Loan',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '92qq1pgp': {
      'en': 'Other',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0ena8ip9': {
      'en': 'Please select what kind of Account...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jpavqzma': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ck4wkfxe': {
      'en': 'Source Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'iy11i9yj': {
      'en': 'Enter source name...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lljo571u': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gpf0bbl8': {
      'en': 'Enter source name...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r9ydgouh': {
      'en': 'Create Payment Source',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ro0op7rj': {
      'en': 'Add Wallet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2sxctoc7': {
      'en': 'Source',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AddTransaction
  {
    '6cb881qe': {
      'en': 'example',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'j9y0ullm': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'drxj8fg1': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qv1kzk04': {
      'en': 'Select Household*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6mox1rnq': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'srs8ebvc': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '02i8v3nh': {
      'en': 'Select Payment Source*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g5ahcttr': {
      'en': 'Debit',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yn02ubpd': {
      'en': '-',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7sd71dvf': {
      'en': '+',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dvk73hmh': {
      'en': 'Please Select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xslgp9zr': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jijiw4uw': {
      'en': '+/-',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'cc1crqyo': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xlqsqmp9': {
      'en': '0.00',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o1cso2hp': {
      'en': 'Description*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r79yylov': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qjletz0c': {
      'en': 'Tags',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '975z1mda': {
      'en': 'Comma Separated List',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '59xgdtb8': {
      'en': 'Cleared?                                                 ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'z8ztxd74': {
      'en': 'Upload Receipt',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v1uh6xgd': {
      'en': 'Add Transaction',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hiqjw0eb': {
      'en': 'Add Transaction',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'axa67esb': {
      'en': 'Transaction',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditUser
  {
    '648tohc5': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'nnhjo7e1': {
      'en': 'Phone Number',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yp5imn4x': {
      'en': 'Update Profile',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ihlfs3p2': {
      'en': 'Edit Profile',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1nhlwor7': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditMembers
  {
    'f5ymmlet': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'h0n074ig': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6asprp4e': {
      'en': 'Select Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'z1mwdnyl': {
      'en': 'Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pmu5ve7d': {
      'en': 'Email',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'h3h76udw': {
      'en': 'Joined',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mzwo7etp': {
      'en': 'Action',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '18sxciiu': {
      'en': 'Edit Members',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'uopp4d42': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Ledger
  {
    'fi6ceitj': {
      'en': 'example',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8rb6mvvv': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'teylsa79': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oadh8i46': {
      'en': 'Select Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rcl2s0p2': {
      'en': 'View Spending Habits',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    't9s92rrf': {
      'en': 'Total Spent This month: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lxij45w4': {
      'en': 'Safe To Spend: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '37wyhkz3': {
      'en': 'Ledger',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'z67rchgz': {
      'en': 'Ledger',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Settings
  {
    'dqng4nv7': {
      'en': 'Change Email / Phone number',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'urvy98o6': {
      'en': 'Add Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gr5tzrtt': {
      'en': 'Invitations',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vki2yai0': {
      'en': 'Edit Members',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'b61v90ua': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'kewqnqb6': {
      'en': 'Notifications',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r8wk2rgp': {
      'en': 'Light Mode',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd6ph9sip': {
      'en': 'Dark Mode',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'old6drlr': {
      'en': 'Settings',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9lph6yzp': {
      'en': 'Settings',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // SupportPage
  {
    'ytq0by5i': {
      'en': 'Welcome to support',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v7jz0bw3': {
      'en': 'How can we help you?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bmlmxjj6': {
      'en': 'Email Us',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ii6q1e3g': {
      'en': 'Search FAQs',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '42mage7j': {
      'en': 'Review FAQ\'s below',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'h9wzzrdf': {
      'en': 'How do I download Code?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6zvypkxu': {
      'en':
          'Showcase a couple of eye-catching screenshots or mockups of your UI Kit to capture attention and give users a glimpse of what they can expect.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '33bks0oa': {
      'en': 'How do I download Code?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ndw152b2': {
      'en':
          'Showcase a couple of eye-catching screenshots or mockups of your UI Kit to capture attention and give users a glimpse of what they can expect.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'drnh2dtk': {
      'en': 'How do I download Code?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5nyjytd9': {
      'en':
          'Showcase a couple of eye-catching screenshots or mockups of your UI Kit to capture attention and give users a glimpse of what they can expect.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'klkrn7wu': {
      'en': 'Create Ticket',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'grhfihfb': {
      'en': 'Chat Now',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ockjgpfk': {
      'en': 'Get support',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7nlmrujd': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Incomes
  {
    '8hecepyl': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm95pe4l2': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fqglnn4b': {
      'en': 'Your Incomes',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mye01jkr': {
      'en': 'Below is a list of your Incomes for the month',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2msslbpg': {
      'en': 'Acme Inc',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wolvdukh': {
      'en': 'Total ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '07gqawdr': {
      'en': 'Next Payday ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5huamn5b': {
      'en': 'Incomes',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xkkd5m13': {
      'en': 'Incomes ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // PaymentSources
  {
    'eg33hesr': {
      'en': 'example',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gsemlu16': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '3a1ra9an': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dk9jnu6h': {
      'en': 'Select Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'thnemytb': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ka2j9ssj': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Export
  {
    'zreuhkb1': {
      'en': 'Export',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5159rhj6': {
      'en': 'Reports',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Bills
  {
    'hxb5ji1p': {
      'en': 'example',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2oqt8a86': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qij3am63': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'umkrgsf1': {
      'en': 'Select Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'frr71lhz': {
      'en': 'Due',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ov331tcb': {
      'en': 'DUE',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'c3j9yic1': {
      'en': 'PAST DUE',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '02zggwa4': {
      'en': 'Paid',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2k2k7vfa': {
      'en': 'PAID',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dyrxz4j4': {
      'en': 'Future',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm5iyw6s4': {
      'en': 'Not Due Yet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0kyl2p6o': {
      'en': 'Bills',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ttmje8k7': {
      'en': 'Bills',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // BillDetails
  {
    'cpk51b2m': {
      'en': 'Name: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ep6wk3k5': {
      'en': 'Amount: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e2p8a4bg': {
      'en': 'Frequency: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0nxsi21t': {
      'en': 'Category: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '58jmo294': {
      'en': 'Description: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '75qcqdik': {
      'en': 'Day of the Month Due: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'nb89soq9': {
      'en': 'Status: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ok0j6grh': {
      'en': 'Created At: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8ooplkwr': {
      'en': 'Login Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'j96w6oru': {
      'en': 'Biller Website: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vvgav8lp': {
      'en': 'Username: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8v2mv767': {
      'en': 'Password: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ncn4awxv': {
      'en': '********************',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bxcf6zx0': {
      'en': 'Username and Password Stored Securely',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vjp9wzjv': {
      'en': 'Bill Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qr8b8pmj': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // TransactionDetails
  {
    't2urdtuo': {
      'en': 'Transaction Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6z25bdwi': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8ihgnfl6': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lvgz9n0f': {
      'en': 'Cleared?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ovi6bo69': {
      'en': 'TransactionDate',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0wqdvzy3': {
      'en': 'Created At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dmcmufu1': {
      'en': 'Updated At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '96155r76': {
      'en': 'Transaction Type',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pwgfruwk': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'p9surem7': {
      'en': 'Updated By',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l15uojq6': {
      'en': 'Tags',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'f60bc50b': {
      'en': 'Payment Source Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e5658oi2': {
      'en': 'Payment Source',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gyvr51yd': {
      'en': 'Running Total',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pjqyp5lk': {
      'en': 'Payment Type',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '36170s1s': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qd6hqt9e': {
      'en': 'Created At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ki3664fv': {
      'en': 'Updated At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '46nxfr7m': {
      'en': 'Transaction Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm8c2hfnm': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // IncomeDetails
  {
    'n7s2rlty': {
      'en': 'Income Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hq2rzsun': {
      'en': 'Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1gzga15u': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6olynats': {
      'en': 'First Payday',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vmmh318c': {
      'en': 'Frequency',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oesdwhvr': {
      'en': 'Created At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd56uzuns': {
      'en': 'Updated At',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'a13honax': {
      'en': 'Household',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's4jxjqy1': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AddIncome
  {
    'we9ipn6g': {
      'en': 'Income Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rc7sf4xp': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'zx7xm0en': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oull17fa': {
      'en': 'One Time',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7dqsax74': {
      'en': 'Weekly',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xfu2ef6o': {
      'en': 'Bi-Weekly - Every 2 weeks',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ntv407h2': {
      'en': 'Monthly - Every 30 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'uvx33bbo': {
      'en': 'Bi-Monthly - Every 60 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7x3iamd7': {
      'en': 'Quarterly - Every 90 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd0jf1td8': {
      'en': 'Annually',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xlitdyv6': {
      'en': 'How Often Do You Get Paid?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'y2owf7ix': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fae4ldn2': {
      'en': 'One Time',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'j8xwab89': {
      'en': 'Weekly',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ci0498nk': {
      'en': 'Bi-Weekly - Every 2 weeks',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'btu2rhai': {
      'en': 'Monthly - Every 30 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    't5dv4hse': {
      'en': 'Bi-Monthly - Every 60 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4avz4wz8': {
      'en': 'Quarterly - Every 90 days',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hrw5syxr': {
      'en': 'Annually',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'kb9e4o15': {
      'en': 'Connect To Payment Source',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6gslvggc': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'uzkzq8av': {
      'en': 'Add Income',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wrua2ny7': {
      'en': 'Add Income',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0qp21nl4': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Notifications
  {
    'of9s4gmg': {
      'en': 'Notifications',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'diwgwdua': {
      'en': 'Email Address: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'efx2ixfe': {
      'en': 'Title: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9lj2cyo7': {
      'en': 'Message: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's1wo1npo': {
      'en': 'Created At: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'trq7cbq6': {
      'en': 'Updated At:',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '3pr7hfv2': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Categories
  {
    'e9eu270c': {
      'en': 'January',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9bdewwbe': {
      'en': 'Februrary',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gy1rhgxl': {
      'en': 'March',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'b8sg7tgb': {
      'en': 'April',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'f75vgn1f': {
      'en': 'May',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'iwrmgggz': {
      'en': 'June',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dhrwqosw': {
      'en': 'July',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hk82cqkj': {
      'en': 'August',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0tb3bbay': {
      'en': 'September',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9rf7m25d': {
      'en': 'October',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    't6ai1k39': {
      'en': 'November',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lnxo85uk': {
      'en': 'December',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'eecap8j6': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'byyicnyz': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pu1dfiba': {
      'en': 'Month',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ifg1y9a9': {
      'en': '2024',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v97s6izf': {
      'en': '2025',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q901mejj': {
      'en': '2026',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'n5d877pr': {
      'en': '2027',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tbtxnlfl': {
      'en': '2028',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e3u8blbm': {
      'en': '2029',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '763vnuio': {
      'en': '2030',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4kke73pn': {
      'en': '2031',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7psf9hai': {
      'en': '2032',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dcqc7tcc': {
      'en': '2033',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1cxslyr5': {
      'en': '2034',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hdbx5ykm': {
      'en': '2035',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'npdqj4b2': {
      'en': '2036',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g7v3c6l8': {
      'en': '2037',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2srrcz9j': {
      'en': '2038',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '854lwgvc': {
      'en': '2039',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0ub55hrx': {
      'en': '2040',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'pj6lmue4': {
      'en': '2041',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'k9lw6eo8': {
      'en': '2042',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'up7ac3xl': {
      'en': '2043',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'kagnn1ku': {
      'en': '2044',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2zdf29ox': {
      'en': '2045',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mtiyqlv2': {
      'en': '2046',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mgb0bg4t': {
      'en': '2047',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bw8ddpjn': {
      'en': '2048',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qfyb1pgh': {
      'en': '2049',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'odymvswt': {
      'en': '2050',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bmutklbl': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8qvqb7n6': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '90y82496': {
      'en': 'Year',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o3s9olcs': {
      'en': 'Month to Date',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xm5m0hay': {
      'en': 'Year to Date',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8vcz8tbb': {
      'en': 'Categories',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xgncgens': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // AddBill
  {
    '3dhe25b2': {
      'en': 'Add Bill',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'a7ftd4zh': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8jhg2xde': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'h58me0s8': {
      'en': 'Payment Source*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '3mw8m97t': {
      'en': 'Name of Bill*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'iawlktxl': {
      'en': 'Amount*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2d2ku081': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rofbjklk': {
      'en': 'Bill',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'sc7asjte': {
      'en': '1st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm3ffx2q7': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q632u26w': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'w5chra2x': {
      'en': '4th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'zb7x5yk2': {
      'en': '5th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mgogy3d2': {
      'en': '6th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g5mq3lyr': {
      'en': '7th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'huaz5xx9': {
      'en': '8th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lrp1gt6s': {
      'en': '9th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lgrykxf2': {
      'en': '10th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '242v42vd': {
      'en': '11th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lpsagjdo': {
      'en': '12th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '73uo8uyh': {
      'en': '13th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vr9139yi': {
      'en': '14th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'phemj3qo': {
      'en': '15th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's6z57upd': {
      'en': '16th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'zd5ojm2b': {
      'en': '17th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ot39ma9z': {
      'en': '18th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dl6b0c2p': {
      'en': '19th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's7b8uxzd': {
      'en': '20th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4f04vtz3': {
      'en': '21st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6cesc1uv': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6fuk3ob3': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vbajqnf9': {
      'en': '24th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tw6z6yty': {
      'en': '25th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'w4gozext': {
      'en': '26th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tc1z3ag5': {
      'en': '27th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vbdwxgz1': {
      'en': '28th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o2gvnsby': {
      'en': '29th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xo4aioz8': {
      'en': '30th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v39le4y0': {
      'en': '31st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r77k9oce': {
      'en': '1st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jv67qlbu': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '23t6m2gy': {
      'en': 'Day Of the Month Due*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'w9cubujr': {
      'en': 'Monthly',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'cmduuiiw': {
      'en': 'Once',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xsdjvpdm': {
      'en': 'Weekly',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wayigelf': {
      'en': 'Bi-Weekly (Every 2 weeks)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vgrera01': {
      'en': 'Monthly (Every 30 days)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5it388a0': {
      'en': 'Bi-Monthly (Every 60 days)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lzt56jzr': {
      'en': 'Quarterly (Every 90 days)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '57b95gqc': {
      'en': 'Annually (Yearly)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'joh0rz56': {
      'en': 'Frequency',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dsg0cjxx': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'spgzx57p': {
      'en': 'Frequency*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'woiqap2j': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'n025alnj': {
      'en': 'Biller URL',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ti9rgtbn': {
      'en': 'Please Provide a link to the biller\'s webpage',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'cgjxgxb2': {
      'en': 'Username',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd18r914v': {
      'en': 'Biller Username',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o8oi74cz': {
      'en': 'Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r6pi1g0y': {
      'en': 'Biller Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lalf0hgl': {
      'en': 'Add Bill',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'c3unpp3a': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // PaymentSourceDetails
  {
    '4v6caq3g': {
      'en': 'Wallet Details',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dw6q7vrm': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // QueryTransactions
  {
    'o9uf9t3v': {
      'en': 'Search',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm7hqji8i': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditBill
  {
    'wke78qjn': {
      'en': 'Name',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's4ok44f5': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '99cvlthp': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9dc2wx2b': {
      'en': 'Once',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l6ho10k9': {
      'en': 'Weekly',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's9gze5jm': {
      'en': 'Bi-Weekly ( 14 days)',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'u41h179g': {
      'en': 'Monthly ( 30 days )',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'z4le7m7y': {
      'en': 'Bi-Monthly (60 days )',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gluezox8': {
      'en': 'Quarterly ( 90 days )',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ndxdfvjb': {
      'en': 'Annually',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'e01x5dwq': {
      'en': 'Frequency',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'v3zqazvc': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4scucxos': {
      'en': 'Frequency',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gz9z8xxn': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q8lws8af': {
      'en': '1st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5vm8pfju': {
      'en': '2nd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1mtk8n37': {
      'en': '3rd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dbreicht': {
      'en': '4th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'udwa06b4': {
      'en': '5th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fzvoqfgc': {
      'en': '6th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'guuyfbpg': {
      'en': '7th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hav19war': {
      'en': '8th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jgj1hq42': {
      'en': '9th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '61h9ilz6': {
      'en': '10th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ivvlqmsi': {
      'en': '11th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mnbxlzss': {
      'en': '12th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'd4szkz4u': {
      'en': '13th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xfomp78o': {
      'en': '14th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dpm9v930': {
      'en': '15th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ailpt9oe': {
      'en': '16th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'z2d6s8xe': {
      'en': '17th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '3tubel1g': {
      'en': '18th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7jw5ksuw': {
      'en': '19th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vsgn26tn': {
      'en': '20th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g268bxkk': {
      'en': '21st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'c24qeah5': {
      'en': '22nd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'n1xtjluu': {
      'en': '23rd',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'g8460jyx': {
      'en': '24th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4kdretsw': {
      'en': '25th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bw1bseyf': {
      'en': '26th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '621furi7': {
      'en': '27th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'b1cx5x3n': {
      'en': '28th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l105h6pc': {
      'en': '29th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wa1inmfi': {
      'en': '30th',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'sxvqvrmv': {
      'en': '31st',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7ozy6rih': {
      'en': 'Day of the Month Due',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wobslc6z': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'x3mcb6sk': {
      'en': 'Cleared',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gxhbl97w': {
      'en': 'Pending',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'biy9kiog': {
      'en': 'Cleared?',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'n288og04': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7ngmjokn': {
      'en': 'Status',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yf31nx2n': {
      'en': 'Biller URL',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'nm1v0zy5': {
      'en': 'Username',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vurkmq5b': {
      'en': 'Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tvr7v8jq': {
      'en': 'Edit Bill',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0e3oj3yl': {
      'en': 'Edit Bill',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1s0a9szv': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditIncome
  {
    'ddx4wv1b': {
      'en': 'Edit Income',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lw6miq56': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Threshold
  {
    'stkdp365': {
      'en': 'Threshold',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'a6fulzbw': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'a530epg0': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'o69rvk6o': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9xqbn850': {
      'en': 'Select Household*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2cmw9w8r': {
      'en': 'Option 1',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4b0kuftc': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oejvx8o8': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6clu8e8h': {
      'en': 'Select Wallet*',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jfaje44c': {
      'en': 'Set Threshold',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bvvp6uaj': {
      'en': 'View Threshold Breakers',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'fmqngmet': {
      'en': 'Description: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2ovxahhu': {
      'en': 'Date: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l1btfjn1': {
      'en': 'Amount: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'du9pdkqr': {
      'en': 'Running Total: ',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'odolg6eo': {
      'en': 'Threshold',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditNotification
  {
    'o1dwevtb': {
      'en': 'Edit Notification',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lbmvqzmy': {
      'en':
          'Notifications are created by creating a Bill. Bill Notification dates can be added on the Add Bill Page.',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tm9hwe4r': {
      'en': 'Title',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '77lr9mnd': {
      'en': 'Message',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0cj57rfs': {
      'en': 'Edit Notification',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8dl0db1o': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // EditTransaction
  {
    'vqap2xom': {
      'en': 'Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'kgwlb32m': {
      'en': 'Transaction Date',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bdmuypo4': {
      'en': 'Tags',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm9j6ef06': {
      'en': 'Comma Separated List',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'brk00jnf': {
      'en': 'Category',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'l7b2ij55': {
      'en': 'Description',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8xbwvi7r': {
      'en': 'Transaction Type',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'neow3l96': {
      'en': 'Add',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'cxesbr6v': {
      'en': 'Subtract',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2ybb0ce2': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'clfczwux': {
      'en': 'Status',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qs0tglvt': {
      'en': 'Cleared',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6e3hfm46': {
      'en': 'Pending',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'oki5snjx': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '1tfkjbhj': {
      'en': 'Wallet',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'cbox33xq': {
      'en': 'Cleared',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2em135mo': {
      'en': 'Pending',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qor4umsl': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'mg9frbzs': {
      'en': 'Click Image to edit',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8xhc1ul1': {
      'en': 'Edit Transaction',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6g8fqanz': {
      'en': 'Edit Transaction',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'stlzc6qu': {
      'en': 'Home',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // passwordfield
  {
    's9udb7tj': {
      'en': 'New Password',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // SearchTransactions
  {
    '9982x6q3': {
      'en': 'Keyword Search',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '05bp02dn': {
      'en': 'Search Everything',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9wvcyc0y': {
      'en': 'Search',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Filter
  {
    'lnds6s8r': {
      'en': 'Filter Options',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ocldaj3l': {
      'en': 'Min Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '7gd68aub': {
      'en': 'Max Amount',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hk22ysw5': {
      'en': 'Search',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '00235yee': {
      'en': 'Cleared Only',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'jrn120to': {
      'en': 'Current Month Only',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9io7dr53': {
      'en': 'Month',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'x9g489v3': {
      'en': 'Year',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ljlqib9m': {
      'en': '1 Januaary',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9gj21wo4': {
      'en': '2 February',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'smhodqik': {
      'en': '3 March',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'whezd4ws': {
      'en': '4 April',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '2zsski3u': {
      'en': '5 May',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'r4dtoxr1': {
      'en': '6 June',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'zpgruheb': {
      'en': '7 July',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gax2lpsi': {
      'en': '8 August',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4hdopud8': {
      'en': '9 September',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'u079zxlb': {
      'en': '10 October',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'f1qtf7zi': {
      'en': '11 November',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vm8k4dax': {
      'en': '12 December',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gfyxrxzd': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm5857s2k': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gmej8zwc': {
      'en': '2024',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lhfdxzcp': {
      'en': '2025',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qikyu60m': {
      'en': '2026',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ycbjduzc': {
      'en': '2027',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ldearaqy': {
      'en': '2028',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'h1x6slnz': {
      'en': '2029',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'do0qflx6': {
      'en': '2030',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '13lm3f23': {
      'en': '2031',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'me6ny26p': {
      'en': '2032',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '6epc44p7': {
      'en': '2033',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'c05i2s1u': {
      'en': '2034',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '25hp7iif': {
      'en': '2035',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wba2ow8e': {
      'en': '2036',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ftq89sks': {
      'en': '2037',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yrd1r451': {
      'en': '2038',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4y1mkb8c': {
      'en': '2039',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'biqk08s5': {
      'en': '2040',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '4iolkd0i': {
      'en': '2041',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'il7ar4ba': {
      'en': '2042',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '5haclh3b': {
      'en': '2043',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '9nk1hrrb': {
      'en': '2044',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '97ppqsp6': {
      'en': '2045',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'uhszsqd8': {
      'en': '2046',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'yg47rckn': {
      'en': '2047',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rrz6ys9z': {
      'en': '2048',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tyz0c65p': {
      'en': '2049',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '8g4cpr3m': {
      'en': '2050',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rbuy9zv2': {
      'en': 'Please select...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rgalr3kn': {
      'en': 'Search for an item...',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    '57fllogz': {
      'en': 'Please provide Camera access so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hqjyswpi': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'gqnpf09i': {
      'en': 'Please provide Biometrics access for quicker login',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'rrtsqja0': {
      'en': 'Please provide Calendar access for bills',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0jvhuji2': {
      'en': 'Please provide Camera access so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'u9m5mzh6': {
      'en': 'Please provide access to Photo Library so you can upload receipts',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '55v3srad': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'es8762ji': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'qsxzzvc2': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'vnwtrchj': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'xclnr7ni': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '53up8ruf': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'hnr9h57q': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '0z1wal53': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'miuzrtvl': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'm8locfsf': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'klc8lp4j': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'dfsifyux': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '795j3gj6': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wd7x988o': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'khko1hkh': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'tumf7sjr': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wcro1mys': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'wxjrdbd9': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'ft0gisuq': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'bdov1cte': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    '70czdhee': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'plomdrwt': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'q49jhonk': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    'lagf6jd9': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
    's1lod96p': {
      'en': '',
      'es': '',
      'fr': '',
      'tl': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
